### ISSUE TITLE
`pragma: whitelist secret` doesn't support additional text

### ISSUE THREAD

**Issue by domanchi** [Yelp/detect-secrets#117]
`detect-secrets` doesn't complain about:

```
whitelisted_api_key: "DEADBEEF1234" # pragma: whitelist secret
```

but complains about:

```
whitelisted_api_key: "DEADBEEF1234" # pragma: whitelist secret blah
```

If it's a comment, it should support text that follows it.

**Comment by asdrubalos** [comment]
Help me please.
how write # pragma: whitelist secret in java?

I have 2 false positive:
1)
this.clientSecret = clientSecret; //# pragma: whitelist secret
2)
String x =", clientSecret='" + this.clientSecret +"'"; //# pragma: whitelist secret

**Comment by KevinHock** [comment]
Hi @asdrubalos, I believe you can put a space after the `//`

When I scan
```java
$ cat test.java 
API_KEY = "blahwww"
API_KEY = "blah-blah-but-actually-not-secret" # pragma: whitelist secret
1)
this.clientSecret = clientSecret; // # pragma: whitelist secret
2)
String x =", clientSecret='" + this.clientSecret +"'"; //# pragma: whitelist secret
```
with the latest detect-secrets (0.12.0) `this.clientSecret = clientSecret;` was reported if I did not have a space between `//` and `#`

**Comment by KevinHock** [comment]
Also @asdrubalos , I will be sure to make quotes required for keyword secrets in `.java` files https://github.com/Yelp/detect-secrets/pull/133 

Thank you for the report 👍

**Comment by KevinHock** [comment]
Actually just `//` should work as well, e.g. `// pragma: whitelist secret`, this is due to this PR https://github.com/Yelp/detect-secrets/pull/105/files

We should document that better though 👍  We'll be sure to do that too

**Comment by KevinHock** [comment]
This was solved by the wonderful @dgzlopes
