### ISSUE TITLE
Create performance testing benchmarks

### ISSUE THREAD

**Issue by domanchi** [Yelp/detect-secrets#130]
This tool is meant to be fast. Not blazingly fast, but fast nonetheless. Before we can optimize on speed though, we need to create some testing frameworks to accurately measure performance of the engine.

This way, we can make improvements, and note the speed differential for different regexes / features.

**Comment by KevinHock** [comment]
It would also be really nice to maybe have an option of running the tool and having it say which files took the longest to scan.

**Comment by domanchi** [comment]
This is finalized in: https://github.com/Yelp/detect-secrets/pull/187.
