### ISSUE TITLE
Line exclude regex just for keyword detector

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#131]
In https://github.com/Yelp/detect-secrets/pull/127 we added a line exclude for _all_ plugins and reverted https://github.com/Yelp/detect-secrets/commit/15a6e6a0fe4884925c15f4378667b2d8f2e16cab, which was a line exclude regex for just the high-entropy plugins, this was partially due to imagined use-cases of things someone may want to exclude from all plugins e.g. lines whose first non-whitespace character is a`#`, and general cleanliness (DRY).

The keyword detector however, is a young plugin with kind of an ambitious goal, and users shouldn't have to add to the [`FALSE_POSITIVES`](https://github.com/Yelp/detect-secrets/blob/50e2edf46453eacbc1e42144cf51bb0f5ce2618c/detect_secrets/plugins/keyword.py#L49) dict things that may be specific to their codebases, and version bumps won't need to happen to trim false positives.

This is a good-first-issue, b/c it was done very similarly in https://github.com/Yelp/detect-secrets/commit/15a6e6a0fe4884925c15f4378667b2d8f2e16cab

**Comment by hpandeycodeit** [comment]
@KevinHock I would like to work on this.

**Comment by KevinHock** [comment]
Awesome @hpandeycodeit, let me know if you need any help 👍

**Comment by hpandeycodeit** [comment]
@KevinHock Are we looking to change the same files as in this commit [15a6e6a](https://github.com/Yelp/detect-secrets/commit/15a6e6a0fe4884925c15f4378667b2d8f2e16cab)

**Comment by KevinHock** [comment]
@hpandeycodeit  We will still change `detect_secrets/core/usage.py` and `tests/core/usage_test.py`, except instead of changing `HexHighEntropyString` and `Base64HighEntropyString` we can change `KeywordDetector` to have the option. Instead of an `_add_high_entropy_excludes` function we can add something like a `_add_keyword_exclude` function that adds a `--keyword-exclude` option to the `KeywordDetector`.


Instead of the `detect_secrets/plugins/high_entropy_strings.py` and `tests/plugins/high_entropy_strings_test.py` files. We can change `detect_secrets/plugins/keyword.py` and `tests/plugins/keyword_test.py`
e.g. in `keyword.py` we can add an `__init__` method to take in a new arg, then call super's init method. We can use the new arg to skip strings in the `analyze_string_content` method.

Hope this helps 👍 Let me know if you need me to clarify anything

**Comment by hpandeycodeit** [comment]
@KevinHock Thanks for the clarification. I created a PR. Let me know what you think.

**Comment by KevinHock** [comment]
Awesome, thank you @hpandeycodeit 👍

**Comment by KevinHock** [comment]
Closing as fixed by https://github.com/Yelp/detect-secrets/pull/132
