### ISSUE TITLE
Handle un-scannable files more gracefully

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#141]
Having a bunch of
`INFO: Checking file: some_image.png`
`WARNING: some_image.png failed to load.`
from
https://github.com/Yelp/detect-secrets/blob/9f3d9ee1d186ba8f5a9972540abde580fc3c570a/detect_secrets/core/secrets_collection.py#L310
is not ideal. We know we cannot scan certain files e.g. images, so we should behave more gracefully.

In [`detect-secrets-server`](https://github.com/Yelp/detect-secrets-server) we already have the [`IGNORED_FILE_EXTENSIONS`](https://github.com/Yelp/detect-secrets-server/blob/c7cee5b2814d589d6643376fcfd6023cad1f2039/detect_secrets_server/constants.py#L7 ) tuple we made [to skip files](https://github.com/Yelp/detect-secrets-server/blob/1905e80acf8cdb6318ee5ad416a0e3724755f1c7/detect_secrets_server/storage/core/git.py#L148) like this
```
IGNORED_FILE_EXTENSIONS = (
    '7z',
    'bmp',
    'bz2',
    'dmg',
    'exe',
    'gif',
    'gz',
    'ico',
    'jar',
    'jpg',
    'jpeg',
    'png',
    'rar',
    'realm',
    's7z',
    'tar',
    'tif',
    'tiff',
    'webp',
    'zip',
)
```
maybe we should move it to `detect-secrets`, change it to a `dict`, and use it.

**Comment by dgzlopes** [comment]
Hello! I don't understand why the IGNORED_FILE_EXTENSIONS structure should change from a tuple to a dict. Could you offer some more insight on this?

On the other side, I made this quick fix https://github.com/dgzlopes/detect-secrets/commit/3828be91030c2243b11427649b875912470f2638 on my fork (handling the check inside scan_file() instead of _extract_secrets_from_file()) and seems to work ok. Any idea on where to handle it more gently?

**Comment by KevinHock** [comment]
The reason why I would like to change it to a `dict` is because the only use is an `in` check, which is faster in a hash table (dictionary). It's less for performance reasons and more for knowing how it is used, from seeing the type.

**Comment by dgzlopes** [comment]
Oh! I see. On the other hand (and sorry if this question is stupid) why we can't use a Set()? 

They have both the same time complexity (O(1) for membership checking on the average case [[0](https://wiki.python.org/moin/TimeComplexity#set)]) and both are implemented with a Hashtable. Also our file extensions values fit in one dimension [[1](https://stackoverflow.com/questions/19454970/is-there-a-python-dict-without-values)], are unique and can be unordered. Also the Python docs [[3](https://docs.python.org/3/library/stdtypes.html#set)]  states that they are a good option for membership testing.

[[0](https://wiki.python.org/moin/TimeComplexity#set)] https://wiki.python.org/moin/TimeComplexity#set
[[1](https://stackoverflow.com/questions/19454970/is-there-a-python-dict-without-values)] https://stackoverflow.com/questions/19454970/is-there-a-python-dict-without-values
[[2](https://docs.python.org/3/library/stdtypes.html#set)] https://docs.python.org/3/library/stdtypes.html#set

**Comment by KevinHock** [comment]
Oh, I wasn't clear, I did mean set.
e.g. replacing the `(` with `{` and `)` with `}`

A dictionary without keys is a set, so I kind of used them interchangeably.

**Comment by KevinHock** [comment]
Thanks @dgzlopes! 👍 🎈 🎉 🎂
