### ISSUE TITLE
Audit doesn't highlight on python2

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#150]
Doing e.g. `detect-secrets audit .secrets.baseline` won't highlight the relevant secret, which makes it kind of frustrating to use.

I didn't dive into what is causing this, b/c I switched to a python 3 venv, but we should fix it.

**Comment by domanchi** [comment]
Seeing that [Python2 will be retired Jan 2020](https://pythonclock.org/), I'm comfortable closing this issue as "won't do".

After all, `audit` is used in an adhoc basis, so it doesn't need to be compatible with any legacy systems that might be out there.
