### ISSUE TITLE
Use --exclude-lines from baseline, if there

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#151]
We [somewhat recently](https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#tada-new-features-1) added an `--exclude-lines` option when scanning, that will end up in the baseline here:
```
  "exclude": {
    "files": "...",
    "lines": "(foo)"
  },
```

We might as well not make people do e.g.

```
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline', '--exclude-lines', '(foo)']
```
in their `.pre-commit-config.yaml`, if they already have a line exclude in their baseline.

**Comment by domanchi** [comment]
This is handled in the upcoming v1 release through filters (https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/filters.md). Once the baseline is loaded, all settings are also configured, which carry over any line/file exclusions, as well as other filters (e.g. wordlist, verifiability, etc.)

Closing as done.
