### ISSUE TITLE
Improve docs for plugins based on RegexBasedDetector

### ISSUE THREAD

**Issue by dgzlopes** [Yelp/detect-secrets#170]
Hello! I thought (after reading contributing.md [[0](https://github.com/Yelp/detect-secrets/blob/master/CONTRIBUTING.md)]) that maybe we should apply another format when adding a new plugin based on RegexBasedDetector [[1](https://github.com/Yelp/detect-secrets/blob/70838677d7da6f75aa3fa2d0ea5fc471af42a14c/detect_secrets/plugins/base.py#L130)]. Adding one point for each one looks like too much as they are all (Slack and AWS as an example) the same but with a different regex. 

Maybe something like this?

* **RegexDetector**: checks for all keys matching a regex (Artifactory, AWS, Slack...)

[[0](https://github.com/Yelp/detect-secrets/blob/master/CONTRIBUTING.md)] https://github.com/Yelp/detect-secrets/blob/master/CONTRIBUTING.md
[[1](https://github.com/Yelp/detect-secrets/blob/70838677d7da6f75aa3fa2d0ea5fc471af42a14c/detect_secrets/plugins/base.py#L130)] https://github.com/Yelp/detect-secrets/blob/70838677d7da6f75aa3fa2d0ea5fc471af42a14c/detect_secrets/plugins/base.py#L130

**Comment by domanchi** [comment]
Hey @dgzlopes,

Could you clarify what you mean? In my understanding, Slack and AWS regex tokens are quite distinct, and use different regexes.

**Comment by dgzlopes** [comment]
Yeah sure! I mean that as they are all based on the same detector and as the only variation is the regex, maybe spending one line per detector for saying the 'same' is too much! As an example:

- ArtifactoryDetector: checks to see if Artifactory credentials are present. (This actually exists on the docs)

- SlackDetector: checks to see if Slack credentials are present.

- AWSDetector: checks to see if AWS credentials are present.

- StripeDetector: checks to see if Stripe credentials are present.

That's why I thought that maybe grouping them under the same 'RegexBasedDetectors' dot could be useful. And if some detector "implements" something different or needs some special clarification, It can be moved to its own bullet point.

**Comment by domanchi** [comment]
Oh, gotcha! You're talking about DRYer documentation.

Sure, feel free to cut out a PR if you think this could be clearer.

**Comment by dgzlopes** [comment]
#177 merged. Closing this one.
