### ISSUE TITLE
Output file and formats

### ISSUE THREAD

**Issue by MVrachev** [Yelp/detect-secrets#179]
Are there any plans to add a flag like `-o` or `--output` which will give us the option to save the output in a file?
I ask this because yes, we can use `detect-secrets scan > result.json` in the command line but if I want to call detect-secrets in my code and to save the output from it in a file then `>` is considered as a not valid argument.

Also, do you plan to add other formatting options besides `JSON`?

**Comment by domanchi** [comment]
Short answer, no. Long answer, maybe.

This project was designed with UNIX philosophy in mind: do "one thing" and do it well, and allow the use of other tools to integrate well with this. With this in mind, adding code to adjust formatting options will increase bloat, and is arguably unnecessary when there are tools that can convert JSON to your preferred format already (e.g. I especially like [`uq`](https://github.com/solarkennedy/uq) for this).

However, I do understand the want for obtaining this output and using it in other scripts. A few suggestions:

1. If you're writing in Python, you can just import the library, and [run the relevant code](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/main.py#L56-L58) yourself. There can be some argument made that we should refactor `main.py` to allow easier use of this, but we'll need to see whether there's enough community demand for this feature before investing the time for it.

2. If you're writing in other languages, you can also just shell out, and capture the output.

Python example:
```python
import json
import subprocess

baseline = json.loads(
    subprocess.check_output(
        'detect-secrets scan'.split()
    ).decode('utf-8')
)
```

Ruby example (based on [this](https://stackoverflow.com/a/37329716)):
```ruby
baseline = `detect-secrets scan`
```

If the language you're using doesn't support capturing of shell output, let me know. I'm super curious to find out.

**Comment by MVrachev** [comment]
Thank you for your response! I will find a way to redirect the detect-secret output.
