### ISSUE TITLE
Support scanning multiple specified files on the command line

### ISSUE THREAD

**Issue by MVrachev** [Yelp/detect-secrets#180]
Hi, how can I scan multiple files?

I don't want to scan a whole folder I want to scan only a few specific files.
I want to achieve something like that: `detect-secrets scan test.js test.yaml` but right now when I run it I get: 

![image](https://user-images.githubusercontent.com/16246778/57930580-03d6b480-78bf-11e9-9110-950a9ef4fedc.png)

**Comment by dgzlopes** [comment]
I think (from researching a little on the code out of curiosity) that it's only scanning the first argument (file or directory). Maybe this one is the 'offending' function: https://github.com/Yelp/detect-secrets/blob/1f3322cbe41fdeed76abb164a6c8cbb99b1e9b2c/detect_secrets/core/usage.py#L120

As it's using '?' nargs that reads only one argument if possible [[0](https://docs.python.org/3/library/argparse.html#nargs)]. I'm sure that @domanchi or @KevinHock can throw more light on this issue.

[[0](https://docs.python.org/3/library/argparse.html#nargs)] https://docs.python.org/3/library/argparse.html#nargs

**Comment by domanchi** [comment]
@dgzlopes++

That's accurate. Shouldn't be too hard to modify this such that it can scan multiple files with the command line invocation you suggested: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/baseline.py#L37

**Comment by MVrachev** [comment]
I close it by mistake.

**Comment by domanchi** [comment]
Closing issue, as #188 has been merged.
