### ISSUE TITLE
Feature request: providing a cross-platform bundle for detect-secrets-hook

### ISSUE THREAD

**Issue by lirantal** [Yelp/detect-secrets#184]
Create a one executable bundle release in order to allow developers to easily work with `detect-secrets-hook` in different operating systems, which may or may not have python pre-install, and may require extra setup such as installing python, and then pip.

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
