### ISSUE TITLE
Running scan in --silent mode

### ISSUE THREAD

**Issue by dgzlopes** [Yelp/detect-secrets#185]
Is there any way for running `detect-secrets scan`  with the output supressed? If not, having this option (--silent) might be useful for #181 and for anyone trying to wrap detect-secrets!

**Comment by domanchi** [comment]
Leaving off the verbosity should only make it output the baseline when it's done. Given that in the majority of the use cases, you're going to be running `detect-secrets` to get the baseline, I'm rather against writing a `--silent` flag for this specific case.

Rather, in a shell invocation, you can do:

```
detect-secrets scan > /dev/null
```

or, if you're writing in Python, you can do:

```
import subprocess

# Purposely not saving the output here
subprocess.check_output('detect-secrets scan'.split())

# or pipe to DEVNULL
subprocess.call('detect-secrets scan'.split(), stdout=subprocess.DEVNULL)
```
