### ISSUE TITLE
--scan option is just completely missing

### ISSUE THREAD

**Issue by bakkerthehacker** [Yelp/detect-secrets#19]
The docs suggest using the `--scan` option but it doesnt exist

```
$ detect-secrets --scan > .secrets.baseline
usage: detect-secrets [-h] [--base64-limit BASE64_LIMIT]
                      [--hex-limit HEX_LIMIT] [-v] [--initialize [INITIALIZE]]
                      [--exclude EXCLUDE]
detect-secrets: error: unrecognized arguments: --scan
```

**Comment by KevinHock** [comment]
Hi @bakkerthehacker, thanks for making this. I wasn't able to reproduce, Aaron did rename `initialize` to `scan` in https://github.com/Yelp/detect-secrets/pull/2 but that was before I put the first version on PyPI, did you install from `pip`? It seems you are on an older version.

**Comment by bakkerthehacker** [comment]
Yeah the internal pypi version was out of date
