### ISSUE TITLE
(b)ack audit functionality not present when secret not found

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#204]
[The (b) option](https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#tada-new-features-7) disappears when a secret is not found, unfortunately, making it 'a point of no return' when auditing.
```
Secret:      3 of 5
Filename:    foobar.yaml
Secret Type: Base64 High Entropy String
----------
ERROR: Secret not found on line 3!
Try recreating your baseline to fix this issue.
----------
What would you like to do? (s)kip, (q)uit: b
Invalid input.
```

(I also ran into #189, which makes this problem worse!)

**Comment by dgzlopes** [comment]
As a first time-watch-look analysis, seems like (b) option only appears if `can_step_back` is passed as True in `_get_user_decision()` [[0]](https://github.com/Yelp/detect-secrets/blob/eadaabe4153a6ab714796c2ad3dc4dc84a409b98/detect_secrets/core/audit.py#L387) and the same logic is used both in `audit_baseline` [[1]](https://github.com/Yelp/detect-secrets/blob/eadaabe4153a6ab714796c2ad3dc4dc84a409b98/detect_secrets/core/audit.py#L64) and `compare_baseline` [[2]](https://github.com/Yelp/detect-secrets/blob/eadaabe4153a6ab714796c2ad3dc4dc84a409b98/detect_secrets/core/audit.py#L163) so the same fix should fit both cases! 

Actually,  `can_step_back` flag is toggled if `secret_iterator.can_step_back()` condition if verified (we check on the secret_iterator if we can return) so maybe one way to fix this if I'm not missing any edge case, would be to add this verification as an argument when no secret was found (when `SecretNotFoundOnSpecifiedLineError` exception is thrown) [[3]](https://github.com/Yelp/detect-secrets/blob/eadaabe4153a6ab714796c2ad3dc4dc84a409b98/detect_secrets/core/audit.py#L66) and we call `_get_user_decision()`. 

Something like this (well, just the same we do with a regular secret!):

```python
_get_user_decision(
                can_step_back=secret_iterator.can_step_back(),
                prompt_secret_decision=False,
            )
```
