### ISSUE TITLE
Allow usage of tool from outside git repository

### ISSUE THREAD

**Issue by pascalschulz** [Yelp/detect-secrets#209]
Hi, 

I found that the "get_relative_path" method in "util.py" is not working correctly in case the tool is invoked out of a working directory, in which the Github repos are not stored. 

I used the scan functionality of the tool in a Python module like that: 

`from detect_secrets import main as detect_secrets`
`detect_secrets.main(['scan', 'C:\\Users\\<my username>\\temp\\<file to be scanned>'])`

I had to change the following lines in "util.py": 

```
def get_relative_path(root, path):
 """Returns relative path, after following symlinks."""
     return os.path.realpath(
         os.path.join(root, path),
     )[len(os.getcwd() + '/'):]
```

to: 

```
def get_relative_path(root, path):
    """Returns relative path, after following symlinks."""
    return os.path.relpath(os.path.realpath(
        os.path.join(root, path),
    ))
```

I would appreciate if you could add this or a similar fix to the tool. 

Best, 
Pascal

**Comment by KevinHock** [comment]
Thank you for making this @pascalschulz, I had made #34 previously but was unsure if other people wanted it.

I don't have the code fresh in mind, but based on that other issue, since we shell out to git commands, solving this issue might be more involved than the fix you suggest. I'll comment back once I've looked into it more in-depth.

If I speculate off of memory: It is possible we can fix `scan` via the above code fix, but then we will have messed up baselines, which is a less noticeable way of breaking, so I rather we fix it in it's entirety than implement a partial fix.

**Comment by pascalschulz** [comment]
Hi @KevinHock, 

I completely agree with you that this probably takes more than what I had suggested. I had spent 3 hours yesterday to fix the code for my usecase. I haven't done any other testing, nor have I used the full functionality of the tool. 

I would appreciate if you could look into this more in-depth as you were proposing. 

Best, 
Pascal

**Comment by gpflaum** [comment]
Took me a while to figure out that the path argument only works for paths within the current directory, then I found this issue. The code on the pre-v1-launch branch does give this warning when --verbose is used. The code on master does not. And --all-files also works only on paths within the current directory.
```
[baseline]	WARNING	Did not detect git repository. Try scanning all files instead.
```

**Comment by domanchi** [comment]
@gpflaum : FWIW, there are several assumptions baked into this that need to be resolved before this feature can exist. Namely:

1. Baselines are created with relative file paths from the git root. If we were to run this tool from a different location, how should baselines look like?
2. `PotentialSecret` uses the relative path (from git root) as the `filename` parameter when comparing whether secrets are equal. Given this, would it be possible that two secrets may have different hashes, but reference the same thing (if paths were different)?
3. The `audit` tool leverages these paths to know what to display. This makes some sense when its run from a consistent location (e.g. git root), but if it can be an arbitrary location, how will that affect things?

For these reasons, I'd argue that this is a "fundamental" change that I'd rather wait for the other in-flight v1 branches to merge, before working on this.
