### ISSUE TITLE
Improvement: Cache last-opened files

### ISSUE THREAD

**Issue by OiCMudkips** [Yelp/detect-secrets#210]
In #208 it was pointed out that we aren't too good about ensuring that a scanned file isn't re-opened multiple times in the `audit` functionality. Looking at the `scan` functionality, the situation is the same.

For example, [here](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/base.py#L46) we read all the lines from a file handle in `analyze` itself, then `CodeSnippetHighlighter.get_code_snippet` also opens the whole file again if we find a secret.

I want to just make detect-secrets have a global file cache where detect-secrets will cache all the lines from the last file it read. This will make it so that we open the file for X, we can re-use it for Y, which happens in a couple places (the example above, the "find the plaintext secret" parts of `audit`).

What do we think @KevinHock @domanchi ?

**Comment by OiCMudkips** [comment]
Actually I think it might not be too hard to just alter `get_code_snippet` to accept file lines instead of the filename.

**Comment by domanchi** [comment]
Might be good for `audit`, but not for `scan` methinks.

Scan is designed to go through the entire codebase, and scan all the files. By putting this in global cache, wouldn't we essentially be using "size_of_repository" amount of memory per run? We miiight increase speed a little, but maybe at the cost of memory. Probably also won't scale with `detect-secrets-server`, which scans a bunch of repositories at once.

FWIW, `scan` tries to minimize the latency of file opens by using [`.seek(0)`](https://github.com/Yelp/detect-secrets/blob/13575ede7f9d6f7cb17ac317a19ec5060c97170b/detect_secrets/core/secrets_collection.py#L312).

`audit` on the other hand, has a fixed number of files to scan, so this is less of an issue. I am curious though -- assuming a valid baseline (with files sorted), it seems that once we're done with a file, we don't need that info cached anymore. Maybe we should do a similar strategy with `file.seek(0)` too?

**Comment by KevinHock** [comment]
>Looking at the scan functionality, the situation is the same.

Just to be on the same page, do you have an example of when it is opened multiple times during `scan`?

**Comment by OiCMudkips** [comment]
@domanchi I was imagining that we would only ever cache one file at a time, but I agree that `scan` probably doesn't need it for the `seek(0)` reason you mention, and the fact that I think it can be easy to fix that `scan` can potentially read the same file multiple times in the same run.

My thought for how the cache would work in `audit`:
1) read the file in an `lru_cache`d function that takes in a filename and returns a `list` of file lines
2) if that function is called with the same filename it'll just return the file without actually reading the file
3) if that function is called with a different filename it'll read the new file

---

@KevinHock It's in the initial comment's second paragraph - to be more concrete [this](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/base.py#L56) reads the file once and [this](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/base.py#L63-L64) re-reads the file for every secret found. (I think the "for example" tidbit was misleading, this example is the only one I know of, which is why I think we can just fix `get_code_snippet` to accept file lines instead of a filename)
