### ISSUE TITLE
Not scan files on git version < 1.8.5

### ISSUE THREAD

**Issue by killuazhu** [Yelp/detect-secrets#220]
Git version [before 1.8.5](https://tecadmin.net/install-git-2-0-on-centos-rhel-fedora/) does not support `-C <path>` option.

When running detect-secrets with pre-1.8.5 git version, [`_get_git_tracked_files`](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/baseline.py#L256-L286) would return `None` since the exception is [silently ignored](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/baseline.py#L285-L286). This causes non of the tracked files been scanned.

git help on 1.8.3

```
$ git help
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

**Comment by domanchi** [comment]
Added to FAQ. Closing.
