### ISSUE TITLE
Still getting a report after making secrets invalid

### ISSUE THREAD

**Issue by c0debreaker** [Yelp/detect-secrets#222]
I created a credentials file but it has an invalid format for use with testing detect-secrets. I was expecting it won't return any but it did. What am I doing wrong? I'm thinking of using detect-secrets as a server side git hook instead of cron scanning individual repos.

credentials file
```
$ cat credentials
[default]
aws_access_key_id = SKIAZCNXR66N6IXXXXXX
aws_secret_access_key = YKyGR8kFcXHSrq1wn6efna1/jDcvR

[master]
aws_access_key_id = TSAPIOOVW3BCHXXXXXXX
aws_secret_access_key = jloBH5ifRvD61zVgdRZo9vEg0LNc

[dev]
aws_access_key_id = TSAPJNJIPRGTGXXXXXXX
aws_secret_access_key = 4J8FgCyQjjFxs27rlCAxOtQ45/ZO

[build]
aws_access_key_id = TSAPIYJE6D4YXXXXXXXX
aws_secret_access_key = 0dztyCcXawu8w8qsewquvZg2xouA

[stage]
aws_access_key_id = TSAPIHFSZJ3GKXXXXXXX
aws_secret_access_key = ZmI+2Mc2Q2UxSp12xhiZcIuxce04

[prod]
aws_access_key_id = TSAPJA73NXMOWXXXXXXX
aws_secret_access_key = mMlpk6ATwcTAPIsx/ylReZzPQ9wD

[prods]
aws_access_key_id = TSAPI3D4P3FU7XXXXXXX
aws_secret_access_key = +XIdFcnyITloif4eEBiDG2YKvKrY

[prodp]
aws_access_key_id = TSAPIUR22PYJXXXXXXXX
aws_secret_access_key = H5ockH2/4XpEVk2QIdHIuu9qjlnH

[sandbox]
aws_access_key_id = TSAPZCNXR66N6XXXXXXX
aws_secret_access_key = KyGR8kFcXHSrq1wn6efna1/jDcvR

[free]
aws_access_key_id = TSAPJUJOH3FNDXXXXXXX
aws_secret_access_key = 7Q8UWgRsz9lgRMimepoEuVPvj2bI
```

The result of ` detect-secrets scan credentials` is below
```
$ detect-secrets scan credentials
{
  "exclude": {
    "files": null,
    "lines": null
  },
  "generated_at": "2019-08-14T15:28:23Z",
  "plugins_used": [
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "ArtifactoryDetector"
    },
    {
      "base64_limit": 4.5,
      "name": "Base64HighEntropyString"
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "hex_limit": 3,
      "name": "HexHighEntropyString"
    },
    {
      "name": "KeywordDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "StripeDetector"
    }
  ],
  "results": {
    "credentials": [
      {
        "hashed_secret": "54d05b408759e1caad13e81fdb2d0b3dc7dc69ea",
        "is_verified": false,
        "line_number": 3,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "5ec1e4b54771d0481d0238ecf9e5db8d8a4ac8c0",
        "is_verified": false,
        "line_number": 3,
        "type": "Base64 High Entropy String"
      },
      {
        "hashed_secret": "40d0fbfa834998164311d8f460314c060d5c92e9",
        "is_verified": false,
        "line_number": 7,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "5bb3923bb989c66397c69b4db4e9059bf5b010b0",
        "is_verified": false,
        "line_number": 7,
        "type": "Base64 High Entropy String"
      },
      {
        "hashed_secret": "d3d69c89730f2696800d0b3276fb67cb9b8b8590",
        "is_verified": false,
        "line_number": 11,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "37c1631be01aaba225d7ceef56d5f3222f304ece",
        "is_verified": false,
        "line_number": 15,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "3b747a8328ae79d644ef8a26974a84182e0ac64b",
        "is_verified": false,
        "line_number": 19,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "b1cd16670af6ec305f371658555ae90efabcd205",
        "is_verified": false,
        "line_number": 23,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "288d894aef49f0bec3fbfe7b6bf303760e3baadc",
        "is_verified": false,
        "line_number": 27,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "c01becff75043ace05f9e840421dab424234fbfa",
        "is_verified": false,
        "line_number": 27,
        "type": "Base64 High Entropy String"
      },
      {
        "hashed_secret": "9ee62a2d419a136d22b58efc944371db56a642a3",
        "is_verified": false,
        "line_number": 31,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "01874c139023a708a4e28eee84e6b9096076270f",
        "is_verified": false,
        "line_number": 35,
        "type": "Base64 High Entropy String"
      },
      {
        "hashed_secret": "53a710c27260094934656d9d0d1b967c8cc1ff39",
        "is_verified": false,
        "line_number": 35,
        "type": "Secret Keyword"
      },
      {
        "hashed_secret": "255637dbfcd54815d49f781f12d775d504d19620",
        "is_verified": false,
        "line_number": 39,
        "type": "Base64 High Entropy String"
      },
      {
        "hashed_secret": "a7df8d85d6d6b7804cd225fd309c0a00cf5345eb",
        "is_verified": false,
        "line_number": 39,
        "type": "Secret Keyword"
      }
    ]
  },
  "version": "0.12.5"
}
```

**Comment by dgzlopes** [comment]
Well, you passed a file to detect-secrets on scan mode and it returned all the secrets that It found... I think that it's working as intended!

Instead, if this issue is more about... the AWS secrets have bad formating but another plugin is catching them... You can exclude plugins from the scan with the `--no--plugin-name` flag (e.g. --no-keyword-scan).

**Comment by c0debreaker** [comment]
Got it. Here's what I'm thinking now. If let's say a user makes a commit and my server side hook thinks the branch he pushed contains a secret but user thinks it is not a secret, can I update my detect-secrets script to exclude the value so it becomes whitelisted?

**Comment by dgzlopes** [comment]
So... a developer is pushing a secret to the repo, thinking that it isn't a secret (but it is) and is caught by your detect-secrets server. Why would you want to get the secret whitelisted on the script? Are you referring to the developer's machine script?  I'm not sure if I understand the situation!

**Comment by KevinHock** [comment]
Just to clarify, you want a server-side hook, but without developers having a client-side hook?

You could maybe somehow make Github issues at the reported lines, for the developer to resolve in the PR, I am not sure of anything that does this for Github but would love to hear about it. Or e.g. Jira tickets assigned to the author. Though I agree within the PR would be nicer.

You could have code that uploads past reported secrets (past JSON output from detect-secrets) to S3, and subtracts out previously reported secrets from anything that detect-secrets reports now. Just make sure you add the uploading to S3 as the last step, so in case the service dies unexpectedly, you'll have a duplicate issue and not a false-negative.

**Comment by c0debreaker** [comment]
I like this idea
```
You could have code that uploads past reported secrets (past JSON output from detect-secrets) to S3, and subtracts out previously reported secrets from anything that detect-secrets reports now. Just make sure you add the uploading to S3 as the last step, so in case the service dies unexpectedly, you'll have a duplicate issue and not a false-negative.
```

Yes, I didn't want to implement it on the client side hooks since I've noticed for the past years, not all developers follow. We have thousands of developers too and it will be hard to implement on the client side.

I can easily implement your suggestion by uploading the output of detect-secrets to an s3 bucket as well as making `git push` fail and spitting out the error and  s3 url on the screen of the user who pushed.

**Comment by KevinHock** [comment]
Unfortunately outside of the client-side part, what you do to inform users will probably be highly company specific, but once you have JSON of new secrets added by a developer, it should be possible to come up with something easy to digest, even if it takes some iteration.
You can probably get good metrics too if you `ask people to label tickets as (false|true)-positives` or `see which issues were "Dropped"`, which can be useful for tuning `--line-excludes` server-side or contributing to e.g. keyword detector.

**Comment by c0debreaker** [comment]
Thank you!
