### ISSUE TITLE
Reacting on files that have been whitelisted

### ISSUE THREAD

**Issue by c0debreaker** [Yelp/detect-secrets#226]
I've been playing with `# pragma: allowlist secret` and it works well. However, what if a developer added this whitelisting on a real sensitive information, is there a way for `detect-secrets` to report that whitelisting comment has been added? I'd like to make a report if a file has been found to contain a whitelist comment so that we'll be able to review if the whitelisting comments are legitimate or valid.

```
artifactory_db_password={{ vault.get.password}} # pragma: allowlist secret

vs

artifactory_db_password="Th3CloppyCh1mp" # pragma: allowlist secret
```
I'd like detect-secrets to report on the second example. Something like
```
  "whitelisted": { <--------- A new property
    "ansible/roles/artifactory/templates/postgresql.properties.j2": [
      {
        "hashed_secret": "09343c85545555efc31e6e70b7ea7dcadf854930",
        "line_number": 17,
        "type": "Secret Keyword"
      }
    ]
  },
```

**Comment by domanchi** [comment]
It's certainly a possibility.

Internally, we use off-the-shelf tools to search through code repositories to look for this token. We have found this better than doing this on a per repo basis.

If you think this is a good use case for yourself, feel free to contribute to this repository! We're always accepting community input.

**Comment by c0debreaker** [comment]
Thank you. Will do if I get it working.

**Comment by KevinHock** [comment]
I could have sworn we had an `--ignore-allowlist` option, will investigate later.

**Comment by c0debreaker** [comment]
Cool! Keep me posted. )

I decided on a new approach. Rather than being strict, I'll allow devs to commit but they will be logged so we can monitor and assess the things that detect-screts will find. I mentioned it here https://github.com/Yelp/detect-secrets/issues/225
