### ISSUE TITLE
Add verifiability for Slack webhooks

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#232]
As @dgzlopes helpfully linked to, https://github.com/streaak/keyhacks#slack-webhook shows how we can add this. 

See #194 for an example of how we do this in detect-secrets, e.g. we already have validation for Slack tokens https://github.com/Yelp/detect-secrets/blob/cba044666f1d8a9c8cd2e428fd4f90376d50bf1c/detect_secrets/plugins/slack.py#L30-L39

The parent issue (#153) is [still opened](https://github.com/Yelp/detect-secrets/issues/153#issuecomment-504284806) but figured I'd make this as a `good first issue`.

**Comment by Patil2099** [comment]
@KevinHock Can I work on this?

**Comment by KevinHock** [comment]
Sure thing @Patil2099 :)

Let me know if you have any questions.

**Comment by Patil2099** [comment]
@KevinHock Can you help me a little bit? I might be able to do it for mailchimp and stripe also.
Thanks!
