### ISSUE TITLE
Detection of AWS access key not working

### ISSUE THREAD

**Issue by mirisbowring** [Yelp/detect-secrets#238]
Detect-Secrets does not recognize AWS Access keys. E.X. it's sample data ([Line 7](https://github.com/Yelp/detect-secrets/blob/master/test_data/each_secret.py#L7)) or my personal key. Seems like the aws plugin is not supported by default?

**Comment by OiCMudkips** [comment]
Hi, detect-secrets has a plugin for detecting AWS access keys. Can you share how you're invoking detect-secrets?

**Comment by mirisbowring** [comment]
Oh, sry for the missing details:  
    
I am invoking the scan via `detect-secrets scan test_data/` from the root of the git repository from detect-secrets.  
  
The tool seems to find all "exposed" secrets but not the aws key which is on line 7 of the `test_data/each_secret.py`.  
  
Here are the Results of the scan for this file:  
![image](https://user-images.githubusercontent.com/15715080/64672280-4bcfa780-d46b-11e9-8454-3445c0abba02.png)  
  
As you can see, it did not find the key (line 7).  
I am not sure if it's the correct behavior, that aws keys are not scanned by default?

Regards

**Comment by KevinHock** [comment]
Can confirm this is happening, even weirder, if afterwards you do `--update baseline_you_just_made`, it catches it. Bonkers 😱, will try to see why this is happening.

**Comment by KevinHock** [comment]
Ahh, so this is because of https://github.com/Yelp/detect-secrets/blob/26489629da1be60d13358cd3cf958ee4e97add5f/detect_secrets/plugins/base.py#L75-L76 (added in https://github.com/Yelp/detect-secrets/pull/194).

Which makes it so that, if there is not a working secret key within 5 lines of the access key (AKIA), then detect-secrets does not report it. 

We'll discuss about whether or not we always want to report it was found, just not verifiable. (/ Maybe add a command-line flag to give the current behavior.)

**Comment by KevinHock** [comment]
Going to close this, but I am happy to discuss further.

While it might not be the most intuitive thing we can do, (i.e. you'd expect the tool to be dumber), the rationale is that we do have very high confidence that we're able to verify legitimate keys, so there is little sense in reporting what we are pretty sure will be false-positives.

Do let us know if we somehow don't report (e.g. return False from our verify functions) any legitimate secrets though 👍 like we did in #236 for `v0.12.5`

I'll make a separate issue for [fixing `--update`](https://github.com/Yelp/detect-secrets/issues/238#issuecomment-532907500) for consistent behavior.
