### ISSUE TITLE
Improve the performance of line regexes

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#244]
Due to the way we pass a file to every single plugin, rather than a line, we end up `regex.search`ing the same line P times, where P is the number of plugins. This holds true for both `ALLOWLIST_REGEXES` and ` --exclude-lines`. For large diffs on a tightly provisioned box this can be quite inefficient.

The relevant control flow is as follows

https://github.com/Yelp/detect-secrets/blob/5d3e065e695f8417f99b86402d75288192de48ee/detect_secrets/core/secrets_collection.py#L336-L341

https://github.com/Yelp/detect-secrets/blob/5d3e065e695f8417f99b86402d75288192de48ee/detect_secrets/plugins/base.py#L45-L57

https://github.com/Yelp/detect-secrets/blob/5d3e065e695f8417f99b86402d75288192de48ee/detect_secrets/plugins/base.py#L81-L97

**Comment by KevinHock** [comment]
To put the above differently, we ask "should we skip this line?" number of plugin times, where as we could ask once.

@OiCMudkips pointed out it might make sense to skip 'em after secrets are found, I think they're right.

Let's say the likelihood of having a line hit a `--line-exclude` or `# allowlist` is 1 in 1000, we would need over 1,000 plugins in order for skipping lines before `analyze()`ing to be more efficient, so let's skip them afterwards.

**Comment by killuazhu** [comment]
> To put the above differently, we ask "should we skip this line?" number of plugin times, where as we could ask once.

This makes sense, so the allowed list can be checked once early in the process.


> @OiCMudkips pointed out it might make sense to skip 'em after secrets are found, I think they're right.

Sometimes we find a line might contain several secrets with different types. It would be nice not to skip a line after a secret been found, or give an option to control the behavior.

**Comment by KevinHock** [comment]
> It would be nice not to skip a line after a secret been found, or give an option to control the behavior.

I think we used to have, (my memory is super hazy about this), a really long time ago, an `--ignore-pragma` type option that would still report lines with the `pragma` on them. I might be wrong about that. But you're right it makes a lot of sense to give users that option @killuazhu 👍

**Comment by OiCMudkips** [comment]
Hmm, to be clear, I meant that we should delay the whitelist check until _after_ the secret is found. This means that we only run the whitelist check on # secrets found, instead of (# plugins)*(# lines).

I agree that the `--ignore-pragma` option is a good idea.

**Comment by killuazhu** [comment]
> I meant that we should delay the whitelist check until after the secret is found.

This sounds like a really good idea to reduce some overhead given secret lines are rarer than normal lines. @OiCMudkips

**Comment by KevinHock** [comment]
I can do this one, it's pretty easy.
