### ISSUE TITLE
High Entropy string matchers have false positives on uuids.

### ISSUE THREAD

**Issue by conartist6** [Yelp/detect-secrets#250]
It should be possible to identify random UUIDs which, though they are hex high entropy strings, are generally not secrets. The combination of length, string formatting, and the version bit should be sufficient to match UUIDs, and at least offer the user a configuration option to consider them false positives and quash reporting on them.

**Comment by KevinHock** [comment]
We might be able to add this to #245, as it has recently come up for us as well.


On a private branch, I had added
```python
            if len(result) == 36:
                UUID_RE = re.compile(
                    r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89AB][0-9a-f]{3}-[0-9a-f]{12}$',
                    re.IGNORECASE,
                )
                if UUID_RE.match(result):
                    continue
```
in this area

https://github.com/Yelp/detect-secrets/blob/b21c5f892972ccc60cdb0df356d1091b9226c779/detect_secrets/plugins/high_entropy_strings.py#L92-L97

recently, but I didn't fully flesh it out.

**Comment by KevinHock** [comment]
Could you give an example UUID for posterity @conartist6? I realized on my private branch I had `-` and other metacharacters in entropy plugin I was running and so it makes sense how my plugin caught them, but on master right now we don't have `-`'s in our base64 high-entropy plugin, so I'm curious what part of the UUID we did trigger off of (on master).

**Comment by conartist6** [comment]
5873b5ea-c5cb-40ed-b206-111bb37195f2

**Comment by KevinHock** [comment]
Thanks! :)

**Comment by domanchi** [comment]
This should have been closed a while ago. In v1, this is added as a [filter](https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/detect_secrets/filters/heuristic.py#L48-L57) as well.
