### ISSUE TITLE
base64 high entropy false positive: MongoDB password and username file paths

### ISSUE THREAD

**Issue by docwhat** [Yelp/detect-secrets#266]
I am configuring docker swarm via some YAML files and `detect-secrets` version 0.13.0 is detecting two environmental variable declarations as base64 high entropy strings:

``` yaml
      - "MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_username"
      - "MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_password"
```

This doesn't make sense to me since the only base64 compatible strings are:

**With the alphabet `[a-zA-Z0-9=+/]`**:

- `FILE=/run/secrets/db`
- `INITDB`
- `MONGO`
- `PASSWORD`
- `ROOT`
- `USERNAME`
- `password`
- `username`

**With the alphabet `[a-zA-Z0-9=_-]`**:

- `MONGO_INITDB_ROOT_PASSWORD_FILE=`
- `MONGO_INITDB_ROOT_USERNAME_FILE=`
- `db_password`
- `db_username`
- `run`
- `secrets`

None of those look like a secret and I wouldn't think their entropy would be terribly high.  Especially given their short length.

You can see the exact code, _in situ_ here:

- [`.secrets.baseline`](https://github.com/docwhat/configs/blob/635e55e3614bdb5b590321a03d554251e7339420/.secrets.baseline#L35-L52)
- [The allegedly offending lines](https://github.com/docwhat/configs/blob/635e55e3614bdb5b590321a03d554251e7339420/src/xbrowsersync.yaml#L46-L47)

**Comment by domanchi** [comment]
Interestingly, the base64 character set is actually `[a-zA-Z0-9+/=_-]`, as added by this [commit](https://github.com/Yelp/detect-secrets/commit/e10b9a3e0b2c4e27fafe561c7e2d1c5001cd0fe0). This means that the entire string would actually fit into the charset.

We can see this more clearly by using the `--string` flag.

```
$ detect-secrets scan --string 'MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_username'
AWSKeyDetector         : False
ArtifactoryDetector    : False
Base64HighEntropyString: True  (4.66)
...
```

It does indeed look like a false positive, but I'm not entirely sure what we can do about that. Perhaps if you modify the original string to have spaces between the assignment, it will work? e.g.

```
- "MONGO_INITDB_ROOT_PASSWORD_FILE = /run/secrets/db_username"
```

**Comment by docwhat** [comment]
According to RFC4648 the characters should only include alphanumerics, the equal-sign, and the symbols `/+` or `_-` BUT NOT BOTH.

Detecting a string that has both symbol sets seems wrong. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by domanchi** [comment]
There's some interesting ideas on how we can improve this in https://github.com/Yelp/detect-secrets/issues/234. Merging this ticket with that one.
