### ISSUE TITLE
Encoding Error with ASCII decoder on Unicode Codepoints

### ISSUE THREAD

**Issue by turbo** [Yelp/detect-secrets#268]
I'm using this tool to scan a rather large number of repos (about 4,000). One issue I have been running into is that this tool trips up hundreds of times on encoding issues, causing the entire repo scan to fail, in turn causing me to potentially miss secrets in files not scanned.

First off, all errors look more of less like this:

```text
Traceback (most recent call last):
  File "/usr/local/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/detect_secrets/main.py", line 60, in main
    word_list_hash,
  File "/usr/local/lib/python2.7/dist-packages/detect_secrets/main.py", line 180, in _perform_scan
    should_scan_all_files=args.all_files,
  File "/usr/local/lib/python2.7/dist-packages/detect_secrets/core/baseline.py", line 83, in initialize
    output.scan_file(file)
  File "/usr/local/lib/python2.7/dist-packages/detect_secrets/core/secrets_collection.py", line 234, in scan_file
    self._extract_secrets_from_file(f, filename_key)
  File "/usr/local/lib/python2.7/dist-packages/detect_secrets/core/secrets_collection.py", line 340, in _extract_secrets_from_file
    results.update(plugin.analyze(f, filename))
  File "/usr/local/lib/python2.7/dist-packages/detect_secrets/plugins/base.py", line 129, in analyze
    is_verified = self.verify(result.secret_value, content=str(snippet))
    UnicodeEncodeError: 'ascii' codec can't encode character u'uf000' in position 173363: ordinal not in range(128)
```

Here are the unique error details from my logs (might be worth writing tests for those):

```text
'\\\\u011b'
'\\\\u2018'
'\\\\u2019'
'\\\\u201d'
'\\\\uf000'
'\\\\ufeff'
'\\u011b'
'\\u2014'
'\\u2019'
'\\u201c'
'\\u2026'
'\\u20ac'
'\\u2122'
'\\u260d'
'\\u2705'
'\\uf000'
'\\uf219'
'\\ufeff'
'\\xa0'
'\\xa7'
'\\xa9'
'\\xc0'
'\\xe4'
'\\xf3'
'\\xf6'
'\\xfc'
ordinal not in range(128)
```

I cannot disclose the content of those files. If this is intended behavior (IMO, it shouldn't), please add a flag to keep parsing even when one file fails, and indicate the failure so that ds always scans as much as possible.

**Comment by domanchi** [comment]
Can you share more information about which plugin is failing? As far as I can tell, `ascii` encoding only happens with the JWT plugin ([source](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/jwt.py#L43)).

If this is the source of your issue, maybe it's something to do with the JWT plugin identifying your unicode strings?

**Comment by turbo** [comment]
I'm just running `detect-secrets scan`. I assume it enables all plugins. I can't even see which file causes it to fail, since the exception contains no further info. I assume the best way for you to test this is crafting some files with the offending characters.

**Comment by KevinHock** [comment]
You can do `detect-secrets -v scan` for verbose mode, to see which file is getting checked.

**Comment by rhinoceros** [comment]
you can try upgrade your python to 3.6.
https://github.com/Yelp/detect-secrets/issues/271

**Comment by turbo** [comment]
@rhinoceros Thanks, that did work.
