### ISSUE TITLE
Show helpful error message when plugin not found due to scanning 'new' baseline

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#269]
There is a bad error message that happens when someone has a pre-commit detect-secrets version, and then uses a baseline generated with a newer version of detect-secrets. B/c the 'older' d-s does not have the new plugins, it just fails with an e.g.
```
detect_secrets/plugins/common/initialize.py", line 145, in from_plugin_classname
    klass = globals()[plugin_classname]
KeyError: 'JwtTokenDetector'
```

We can easily catch this, and give a useful error message pretty easily.

Multiple people have ran into this.

**Comment by PritamSangani** [comment]
Hey this issue has cropped up again with the v0.13.1 release. The README still has the v0.13.0 rev number and so when running the precommit hook it is failing:

```
detect_secrets/plugins/common/initialize.py", line 166, in from_plugin_classname
    klass = import_plugins()[plugin_classname]
KeyError: 'CloudantDetector'

```

**Comment by KevinHock** [comment]
This was indeed fixed in the above referenced commit, all that is left to do is bump the version.

Thanks @PritamSangani for bringing this up!
