### ISSUE TITLE
detect-secrets audit file issue

### ISSUE THREAD

**Issue by Staggerlee011** [Yelp/detect-secrets#272]
![Capture](https://user-images.githubusercontent.com/13237981/70543814-f3d83800-1b62-11ea-903e-3681aa39b325.PNG)
Hi, 

When i run a audit of a baseline i get the error: 

`Not a valid baseline file!`

runing on Windows 10, pip install of detect-secrets 

```
detect-secrets  --version
0.13.0
```

Setting up baseline: 

`detect-secrets scan > .secrets.baseline`

Running the audit:

`detect-secrets audit .secrets.baseline`

Not sure how to solve it. any suggestions?

**Comment by domanchi** [comment]
@Staggerlee011, what does your baseline file look like?

**Comment by Staggerlee011** [comment]
hi wouldnt let me upload to here so posted it to [link](https://github.com/Staggerlee011/dotnet/blob/master/.secrets.baseline)

**Comment by Staggerlee011** [comment]
hey @domanchi can you make sense of it?

**Comment by gadeweever** [comment]
Hey same issue here, but tis is on 0.13.1

```
C:\...\spectacular-potatoes [feature/testsecret +2 ~1 -0 !]> detect-secrets scan > .secrets.baseline
C:\..\spectacular-potatoes [feature/testsecret +3 ~1 -0 !]> git add LanguageContact/API/Web.config
C:\..\spectacular-potatoes [feature/testsecret +0 ~1 -0 | +3 ~0 -0 !]> git commit -m "test secret"
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for added large files..............................................Passed
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1

Incorrectly formatted baseline!

C:\..\spectacular-potatoes [feature/testsecret +0 ~1 -0 | +3 ~0 -0 !]> python --version
Python 3.7.2
```
Without pre-commit:
```
C:\..\spectacular-potatoes [feature/testsecret +0 ~1 -0 | +3 ~0 -0 !]>  detect-secrets audit .secrets.baseline
Not a valid baseline file!
```
I'm still trying to investigate why this would be the case but it looks like the actual error is not logged according to: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/secrets_collection.py LINE 63. I don't have a python build setup.

Anyone know why this might be happening?

**Comment by rkapoor028** [comment]
Great Find!

Was facing the same issue, somehow the .secrets.baseline was encoded as UCS-2 LE BOM. Changing the encoding to UTF-8 started working for me again.

**Comment by domanchi** [comment]
This will be added to the FAQ. Closing as done.

**Comment by hramadoss** [comment]
```
git commit -m "testing1"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/harish.ramadoss/.cache/pre-commit/patch1619032024.
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1

Incorrectly formatted baseline!
```
Getting the same error. I checked the default encoding it is set to UTF-8. 
```
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
```
This is on v1.1.0 running Python 3.7.9

**Comment by ssiegel95** [comment]
The FAQ states "Ensure the file encoding of your baseline file is UTF-8". I believe I have but I'm still seeing the issue. I'm doing this under WSL2 (linux).

```
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
```

```
$ detect-secrets scan > .secrets.baseline
$ file -i .secrets.baseline
.secrets.baseline: text/plain; charset=us-ascii
$ detect-secrets audit .secrets.baseline
Nothing to audit!
```

```
$ git commit -m"test" requirements.txt
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/stus/.cache/pre-commit/patch1647634566-18621.
prettier.................................................................Passed
black................................................(no files to check)Skipped
isort................................................(no files to check)Skipped
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1

Incorrectly formatted baseline!
```

**Comment by vteran93** [comment]
Save the file with `UTF-8 with BOM`
