### ISSUE TITLE
Error on Windows when "git" is not in path

### ISSUE THREAD

**Issue by nightwatchcyber** [Yelp/detect-secrets#275]
Getting the following error on Windows when "git" is not in path:
> FileNotFoundError: [WinError 2] The system cannot find the file specified

The stack trace points to _get_git_tracked_files() in this file:
https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/baseline.py#L270

Fails on this code:
```
        with open(os.devnull, 'w') as fnull:
            git_files = subprocess.check_output(
                [
                    'git',
                    '-C', rootdir,
                    'ls-files',
                ],
                stderr=fnull,
            )
```
After some digging, it seems to be caused by the fact that "git" is not in PATH.

It would nice if this would fail more gracefully, perhaps by including a check for "git" being in PATH and also adding this requirement to the documentation.

Thanks!

**Comment by KevinHock** [comment]
Thank you very much for filing this issue @nightwatchcyber. We lack testing on Windows so this is quite helpful.

**Comment by domanchi** [comment]
This will go out in the v1 update. https://github.com/Yelp/detect-secrets/pull/355/commits/1213066211719c4c98c6229eb8346baefb552dcd
