### ISSUE TITLE
exclude files/lines in baseline file not working 

### ISSUE THREAD

**Issue by manesioz** [Yelp/detect-secrets#280]
Hello, first of all, I want to thank you for this great tool. 

After generating a baseline file my repo appears to have >2000 secrets, which is definitely not the case. Many of the false positives are in a `package-lock.json` file and appear as follows: 

```json
"@babel/helper-get-function-arity": {
  "version": "7.0.0",
  "integrity": "sha1-g1ctQyDipGVyY3NBE8QoaLZOScM=",
  "dev": true,
  "requires": {
    "@babel/types": "^7.0.0"
  }
},
...
```
I do not want to consider these as secrets and auditing the file to consider them as false-positives is also not an acceptable solution because the `sha1` hashes are subject to change. 

I edited the `.secrets.baseline` file as follows: 
```
{
  "exclude": {
    "files": "<path_to_file>/package-lock.json",
    "lines": ".*integrity.*"
  },
...
```
I gave both the path to the entire file as well as `regex` to prevent the problematic lines from being considered and neither seems to work. What am I doing wrong?

**Comment by domanchi** [comment]
Hi @manesioz,

For posterity, can you include your invocation for the tool so that we can better reproduce the issue?

**Comment by manesioz** [comment]
Sure thing. 

```sh
user@home:~/ cd repo
user@home/repo:~/  detect-secrets scan > .secrets.baseline
user@home/repo:~/  vi .secrets.baseline #manually edit baseline file to exclude lines/file
user@home/repo:~/  detect-secrets audit .secrets.baseline #this still shows me all the "secrets", including those in the excluded file/lines
```

**Comment by domanchi** [comment]
@manesioz : `audit` reads the baseline as is, and does not rescan the repo. Those `exclude` configurations affect future scans.

Try recreating the baseline with `--exclude-lines` and `--exclude-files` to make your modifications instead.

**Comment by manesioz** [comment]
Awesome thanks, that's a huge help. Cheers

**Comment by rgkobashi** [comment]
This seems to be the tool we need on our team, however I still cannot make it work to exclude files from the regex. I do:

```
$ cd repo
$ detect-secrets scan --exclude-files "myRegex" > .secrets.baseline
$ detect-secrets scan // ignores the regex
```

And also:

```
$ cd repo
$ detect-secrets scan --exclude-files "myRegex" > .secrets.baseline
$ detect-secrets scan --update .secrets.baseline
$ detect-secrets scan // ignores the regex
```

I feel that the order of things is wrong, but cannot figure out what. Spend to much time on this already, I am about to give up on this tool 😔 any help will be appreciate 😄🙏

**Comment by ducva** [comment]
> This seems to be the tool we need on our team, however I still cannot make it work to exclude files from the regex. I do:
> 
> ```
> $ cd repo
> $ detect-secrets scan --exclude-files "myRegex" > .secrets.baseline
> $ detect-secrets scan // ignores the regex
> ```
> 
> And also:
> 
> ```
> $ cd repo
> $ detect-secrets scan --exclude-files "myRegex" > .secrets.baseline
> $ detect-secrets scan --update .secrets.baseline
> $ detect-secrets scan // ignores the regex
> ```
> 
> I feel that the order of things is wrong, but cannot figure out what. Spend to much time on this already, I am about to give up on this tool 😔 any help will be appreciate 😄🙏

First, run `detect-secrets scan > .secrets.baseline` to create the baseline
Second, open `.secrets.baseline` and update your exclude files:

```
  "exclude": {
    "files": ".trufflehog/rules.json|.env.*|.env|^.secrets.baseline$",
    "lines": null
  },
```
Last, run again with `--update` option: `detect-secrets scan --update .secrets.baseline`

**Comment by KevinHock** [comment]
I think this is another example of `detect-secrets-hook` being able to take a baseline, but not `detect-secrets`, being confusing and unintuitive.

**Comment by ammarshadiq** [comment]
Why do when I try to run this command on my cli
`detect-secrets-hook -v --baseline .secrets.baseline exclude_file.txt`

it stills scan `exclude_file.txt` even though `.secret.baseline contains the exclusion of that file:
```
"exclude": {
    "files": "exclude_file.txt|^.secrets.baseline$",
    "lines": null
  },
```
