### ISSUE TITLE
How to pass .secrets.baseline as command line argument?

### ISSUE THREAD

**Issue by jason-ausmus-bfg** [Yelp/detect-secrets#281]
For the pre-commit, I see the following:

```
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
```
If I run `detect-secrets scan --all-files` in Terminal, detect-secrets will continue to find secrets I've audited in the .secrets.baseline. The arg '--baseline' does not exist as an argument for detect-secrets, so how is it using the baseline at all?

**Comment by KevinHock** [comment]
Hi @jason-ausmus-bfg, `setup.py` places two command-line utilities. `detect-secrets-hook` is what you are looking for.

I will make a different issue for documenting this better in the README 👍 Thanks for making this issue!

Also I don't see a reason why we can't add the `--baseline` option to the regular `detect-secrets` utility. It's not how we normally use it, but it still seems helpful to some people.

**Comment by KevinHock** [comment]
(Gonna close this for now, but I will make the other issues later.)

Feel free to ping me if you have any other questions :)

**Comment by jason-ausmus-bfg** [comment]
@KevinHock `detect-secrets-hook` does not allow me to use the `--all-files` flag to check all files.

Do you know of a way that I can do this? Context: I'm attempting to run detect-secrets as an automated step in our CI environment. The command I run needs to know about the baseline and it needs to execute on all files checked in to git.

**Comment by KevinHock** [comment]
It should default to the current directory, if you don't run it with `--all-files`. I think. (`usage.py` can shed some light on this if my answer is unsufficient.)

Behind the scenes, `--all-files` is passed to pre-commit's framework, not `detect-secrets`, which grabs all the git-tracked files, and then gives `detect-secrets-hook` the real list of files.
