### ISSUE TITLE
feature request: automatically scan all files when running `detect-secrets-hook` 

### ISSUE THREAD

**Issue by manesioz** [Yelp/detect-secrets#282]
Ticket which resulted from the conversation [here](https://github.com/Yelp/detect-secrets/issues/246). 

Basically, if you want to integrate `detect-secrets` with [`husky`](https://github.com/typicode/husky) or something like that you will likely need some command which runs your entire repository against your current baseline file. 

Right now that can be done using the `detect-secrets-hook` command, but you have to manually specify which files to scan. I think, instead of this opt-in process, it would make more sense as an opt-out feature (where users specify which files that _dont_ want scanned). Or at the very least, have an `--all-files` tag which accomplishes the same. 

Current: 
```
detect-secrets-hook -v --baseline= ".secrets.baseline" ./**/**
```
Note that you have to use glob to find files (`./**/**`) but if your directory structure is subject to change, you will likely not want this hard-coded path. 

Ideally: 
```
detect-secrets-hook -v --baseline= ".secrets.baseline" --all-files
```

Thanks, let me know if you have any thoughts :)

**Comment by KevinHock** [comment]
The hook is like that on purpose, because it was made for the pre-commit framework.

Can we change this to adding the baseline option to regular detect-secrets?

**Comment by manesioz** [comment]
Yeah that could work too. Any way to run a single command that scans the entire repo and runs a diff with the baseline, force failing a commit if found

**Comment by manesioz** [comment]
Just an update. 
You can get around this by running a delta scan (rather than the whole repo):
```
  "husky": {
    "hooks": {
      "pre-commit": "detect-secrets-hook --baseline .secrets.baseline $(git diff --cached --name-only)"
    }
  }
```
So this feature is probably not as urgent as I thought it was. I'll leave it up to you to decide whether you want to close this or keep it open. Thanks :)

**Comment by domanchi** [comment]
This will be added to the README. Closing as done.
