### ISSUE TITLE
CLI scan exit code 1

### ISSUE THREAD

**Issue by jonrau1** [Yelp/detect-secrets#286]
I may have missed it somewhere but I do not see an easy way to exit with a code 1 when a secret is detected using `scan`. Is there a CLI flag or another method (even if it is hacky) to force this?

I am attempting to integrate detect-secrets into a CI/CD pipeline that has source coming in from CodeCommit and want it to exit with a code 1 to fail my build so the pipeline doesn't progress.

EDIT: To clarify, when I say hacky, I mean less hacky than running this Python script in CI:
```python
import json

try:
    with open('secret-results.json') as json_file:
        data = json.load(json_file)
        if str(data['results']) != '{}':
            exit(1)
        else:
            pass
except Exception as e:
    print(e)
```

**Comment by domanchi** [comment]
Have you tried using `detect-secrets-hook`? Not sure your current invocation, but it certainly returns appropriate error codes.

**Comment by jonrau1** [comment]
Hey @domanchi sorry for the delay, was up late burning oil on this.

My source code repo is AWS CodeCommit, it doesn't support pre-commit hooks, at least not yet.

I am using detect-secrets in CI by running `detect-secrets scan . --all-files > secret-results.json` in CI, and using that above script to force fail the build if there is any detection at all. I am fine with continuing it that way, that small .py script doesn't bloat my source too much, it would be ideal if there was a way to force an exit 1 on `scan` finding anything via a flag or by default though.

**Comment by domanchi** [comment]
You don't necessarily need to use the `pre-commit` framework, in order to use the hook. For example, does this work for you?

```
detect-secrets-hook --use-all-plugins $(git ls-files) 2> /dev/null
```

**Comment by KevinHock** [comment]
I am not against a PR for this, I can't think of a case wherein it'd be unwanted to return a exit code of 1 for the non-pre-commit console script.

**Comment by domanchi** [comment]
Closing as "Won't Fix" due to inactivity from OP. Will add a distinction in the README between the different tools detect-secrets offers to help with different use cases.
