### ISSUE TITLE
IBM COS HMAC Detector False Positives?

### ISSUE THREAD

**Issue by domanchi** [Yelp/detect-secrets#288]
When testing these new plugins, I noticed this plugin was capturing more than what I'd expect it to capture.

### Reproduction Steps

```
$ cat aws_credentials.json
{
    "accessKeyId": "AKIAIOSFODNN7EXAMPLE",
    "secretAccessKey": "81442db33ceee1092586feb635d7b3c5d72257c775ee323414bac8e673d41af3"
}
$ detect-secrets scan aws_credentials.json > baseline
$ detect-secrets audit baseline
```

It looks like the regex is capturing `81442db33ceee1092586feb635d7b3c5d72257c775ee3234`, rather than the full string.

### Proposed Fix

@killuazhu : Does this [password regex](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/ibm_cos_hmac.py#L25) need to be `$` terminated?

**Comment by killuazhu** [comment]
@domanchi That would be a good idea. Would put up a fix for this.
