### ISSUE TITLE
Option to scan through git history

### ISSUE THREAD

**Issue by FYJen** [Yelp/detect-secrets#294]
Love this tool! Really friendly to use.

Does it support git history scanning? From the description, it doesn't look like the tool supports it as a base line file is generated from the current state of a repository. I am wondering if there will be any feature like git history scanning for the users who adopt this tool into their own projects the first time. It will be particularly helpful if I can use this tool to also scan through the git history before open-sourcing a project.

**Comment by domanchi** [comment]
Hi @FYJen, glad to hear you like it!

This tool specifically doesn't do git history scanning, since that's not what it's really designed for. It's designed to be fast, breadth-based scanning, rather than uncovering all the secrets that could have been in your git repository (depth-based).

If you're looking for a tool like that, I'd recommend https://github.com/dxa4481/truffleHog.

**Comment by KevinHock** [comment]
Just want to say, I might do this somewhere down the line, if consensus can't be reached about adding a [3rd console script](https://github.com/Yelp/detect-secrets/blob/0e8925d685f1fe34a1e315045450cd678104648c/setup.py#L31-L34) to do this, I can make a separate package, that has detect-secrets as a dependency, and [call `scan_diff` like detect-secrets-server does](https://github.com/Yelp/detect-secrets-server/blob/f831d9bcb0c0705bc0d55ce6e332f2985cc63287/detect_secrets_server/repos/base_tracked_repo.py#L152-L157).

It's not on my short-term roadmap, but now that we have verifiable secrets plugins, doing a one-time-only verifiable-secrets-only scan across all repos after adding a "from now on" CI step, seems to make a lot of sense.

**Comment by perryzjc** [comment]
> Hi @FYJen, glad to hear you like it!
> 
> This tool specifically doesn't do git history scanning, since that's not what it's really designed for. It's designed to be fast, breadth-based scanning, rather than uncovering all the secrets that could have been in your git repository (depth-based).
> 
> If you're looking for a tool like that, I'd recommend https://github.com/dxa4481/truffleHog.

@domanchi, I've been pondering this topic and have some input. When using an alternative tool to scan commit histories, such tools as [truffleHog](https://github.com/dxa4481/truffleHog) don't have the exact same plugins developed for this project. This is especially relevant for those who have crafted custom plugins for detect-secrets. I feel it would be beneficial to introduce a specific command that allows users to scan the entire commit history, in addition to the default behavior. I'd love to hear your thoughts on this. Thanks!
