### ISSUE TITLE
ahocorasick module is missing after install?

### ISSUE THREAD

**Issue by dkmbw** [Yelp/detect-secrets#296]
Hi, 
i installed detect-secrets via pip3 install on ubuntu 18.04. when i wanted to use the word-list feature i got the error:
```

user@host:kubernetes$ detect-secrets scan --word-list ../words.txt
Traceback (most recent call last):
  File "/home/benutzer01/.local/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/home/benutzer01/.local/lib/python3.6/site-packages/detect_secrets/main.py", line 37, in main
    automaton, word_list_hash = build_automaton(args.word_list_file)
  File "/home/benutzer01/.local/lib/python3.6/site-packages/detect_secrets/util.py", line 28, in build_automaton
    automaton = ahocorasick.Automaton()
AttributeError: module 'ahocorasick' has no attribute 'Automaton'

```

Did i miss anything?

**Comment by dkmbw** [comment]
i just installed pyahocorasick and ran that in ipython and it did not know the Automaton method either.

**Comment by KevinHock** [comment]
(On mobile but) 

What version of the pyahocorasick do you have?

https://pypi.org/project/pyahocorasick/ hasn’t been updated since I added that feature, so the method should definitely be there. As you can see in the docs in that link.

(I assume you did the right pip install command because otherwise an import error would have been thrown https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#telescope-accuracy-1 )

**Comment by dkmbw** [comment]
the installed dependencies are:
``
pip3 list --format=legacy | grep ahocora
ahocorasick-python (0.0.7)
pyahocorasick (1.4.0)
``
and i indeed forgot installing via the in the changelog mentioned command, but after installing it still threw an error:

``
benutzer01@dcsprvm02:~/kubernetes$ detect-secrets scan --word-list ../words.txt
Traceback (most recent call last):
  File "/home/benutzer01/.local/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/home/benutzer01/.local/lib/python3.6/site-packages/detect_secrets/main.py", line 37, in main
    automaton, word_list_hash = build_automaton(args.word_list_file)
  File "/home/benutzer01/.local/lib/python3.6/site-packages/detect_secrets/util.py", line 28, in build_automaton
    automaton = ahocorasick.Automaton()
AttributeError: module 'ahocorasick' has no attribute 'Automaton'
``

**Comment by KevinHock** [comment]
No worries about the pip thing, my bad for not including in the README, I can add that.

I’m not sure how this could be 🤔 Maybe you can post the output of dir(ahocorasick) to see what attributes are available.

I tried looking at existing closed/open issues for the package (cc @WojciechMula) but nothing of this nature popped out at me.

**Comment by KevinHock** [comment]
(E.g. pip install -e .
The source code and add a print statement.)

**Comment by dkmbw** [comment]
Hi, i did the dir() call:

`
benutzer01@dcsprvm02:~/kubernetes$ ipython3 
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ahocorasick

In [2]: dir(ahocorasick)
Out[2]: 
['AhoCorasick',
 'Node',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

In [3]: 

`

That seemed to work?

**Comment by KevinHock** [comment]
Hmm, where did the `ahocorasick-python (0.0.7)` come from? re: Your pip list output. Maybe you can uninstall `pyahocorasick` and see if it also installs the mysterious double-O seven package. I don't appear to have it myself.

I suspect Ahocorasick 007 is overriding what should be there.

My machine output:
```
khock-computer:detect-secrets kevin$ pip list|grep aho
pyahocorasick      1.4.0     
khock-computer:detect-secrets kevin$ python
Python 3.7.6 (default, Feb  9 2020, 18:43:17) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ahocorasick
>>> dir(ahocorasick)
['AHOCORASICK', 'Automaton', 'EMPTY', 'KEY_SEQUENCE', 'KEY_STRING', 'MATCH_AT_LEAST_PREFIX', 'MATCH_AT_MOST_PREFIX', 'MATCH_EXACT_LENGTH', 'STORE_ANY', 'STORE_INTS', 'STORE_LENGTH', 'TRIE', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'load', 'unicode']
>>> automaton = ahocorasick.Automaton()
>>> 
[1]+  Stopped                 /usr/local/opt/python/bin/python3.7
khock-computer:detect-secrets kevin$ pip3 list --format=legacy | grep ahocora

Usage:   
  pip3 list [options]

option --format: invalid choice: 'legacy' (choose from 'columns', 'freeze', 'json')
khock-computer:detect-secrets kevin$ pip3 list | grep ahocora
```

**Comment by dkmbw** [comment]
Hey, i removed both modules and got an error when i tried to installed your requirements-dev file:
`benutzer01@dcsprvm02:~/Repositories/Git/www.github.com/Yelp/detect-secrets$ pip3 install -r requirements-dev.txt 
Collecting coverage<5 (from -r requirements-dev.txt (line 3))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f389ffc4f98>: Failed to establish a new connection: [Errno -2] Der Name oder der Dienst ist nicht bekannt',)': /simple/coverage/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f389ffc4b38>: Failed to establish a new connection: [Errno -2] Der Name oder der Dienst ist nicht bekannt',)': /simple/coverage/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f389ffc4b70>: Failed to establish a new connection: [Errno -2] Der Name oder der Dienst ist nicht bekannt',)': /simple/coverage/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f389ffc4828>: Failed to establish a new connection: [Errno -2] Der Name oder der Dienst ist nicht bekannt',)': /simple/coverage/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f389ffc4a58>: Failed to establish a new connection: [Errno -2] Der Name oder der Dienst ist nicht bekannt',)': /simple/coverage/
  Could not find a version that satisfies the requirement coverage<5 (from -r requirements-dev.txt (line 3)) (from versions: )
No matching distribution found for coverage<5 (from -r requirements-dev.txt (line 3))
`

System ist ubuntu18.04 with updates and python3. :)

**Comment by dkmbw** [comment]
i now removed all my pip packages, deleted caches and reinstalled with pip3 install detect-secrets[word_list].

Now everything works. there has to be some wrong dependency graph cached. We can close the ticket! :)
