### ISSUE TITLE
How to use this with private(GHE) github?

### ISSUE THREAD

**Issue by pradeepkusingh** [Yelp/detect-secrets#299]
May be a dumb question but need some details How to use this with private(GHE) github?

**Comment by killuazhu** [comment]
We use it with private github enterprise instance.  It’s mainly a client side tool, you can ask your developer to run scan on local clone. Then use pre-commit hook to prevent new secrets from leaking

**Comment by OiCMudkips** [comment]
We have a tool at Yelp/detect-secrets-server that scans Git repos en masse as well. Please let us know if you have other questions.
