### ISSUE TITLE
Bug: Blacklist word "@@" is not recognized 

### ISSUE THREAD

**Issue by dkmbw** [Yelp/detect-secrets#300]
Hi,
i have a word list for blacklisted words. like "keyvault=" at the beginning of a string marks the secret not bein in plain here, but in a keyvault. that works.

But i have secrets which are replaced with "@@sometext@@". and i wrote "@@" in the blacklist words file, but still @@ are not recognized and shown as a potential secret in the audit routine.

**Comment by KevinHock** [comment]
I don't think I understand what you're saying.

>i wrote "@@" in the blacklist words file

Can you give more details on what you mean by this?

**Comment by deknos** [comment]
Hi,
sorry, i was offline the last week. i strained fingers on my left hand so i could not type.

i specified a list of words with --word-list to ignore if they appear in a secret. one was 'keyvault=' with this we signified that this is not a secret, but the id for a secret in our keyvault, which has to be replaced. another trigger is @@ which is commonly used in old unix systems. usually variables are denoted like @@secretid@@ and scripts with that replace that via some sort of mechanism.

in the wordlist given via --word-list keyvault= and @@ are named as secretparts which should be ignored, but only secrets which start with keyvault= are ignored. strings with @@ are still not ignored.

**Comment by domanchi** [comment]
@deknos , can you give a minimal example so that we can reproduce this issue on our end?

**Comment by dkmbw** [comment]
Hi, sorry for the absence, my jolted fingers requires more outtime..

Well reproduction seems not as easy. i created a new git repository, and there it does not act up like with my production repository. 

In my Production repository i have a blacklistfile which i use during scanning:

   `detect-secrets scan --word-list=blacklist.txt > results.txt`

then with audit:

   `detect-secrets audit results.txt`

this entry pops up, though i added @@ as a blacklistword:

> Secret:      19 of 39
> Filename:    ourdeployments/dev/justanothercloudservice-helmconfig.yaml
> Secret Type: Secret Keyword
> ----------
> 29:        - som.cloud.domain.com
> 30:  auth:
> 31:    enabled: true
> 32:    type: basic
> 33:    realm: "Authentication Required"
> 34:    secret: '@@NGINX-USERPASSWD-KUBERNETES@@'
> 35:affinity:
> 36:  podAntiAffinity:
> 37:    requiredDuringSchedulingIgnoredDuringExecution:
> 38:    - labelSelector:
> 39:        matchExpressions:
> ----------
> Is this a valid secret? i.e. not a false-positive (y)es, (n)o, (b)ack, (s)kip, (q)uit:  

Perhaps i am doing something wrong, but we have a replacement mechanism, which during deployment sets the marker @@NGINX-USERPASSWD-KUBERNETES@@ with the actual correct encoded password. and in my example repository the filtering works though. i am really puzzled

**Comment by domanchi** [comment]
@dkmbw, this is actually intended behavior.

The `wordlist` feature allows you to provide words that should result in an exact match. Therefore, adding `@@` to the wordlist means it will ignore secrets that are `@@`, but not secrets as you suggested above.
