### ISSUE TITLE
Question: pre commit hook in readme correct?

### ISSUE THREAD

**Issue by dkmbw** [Yelp/detect-secrets#301]
Hi, i am not sure if the pre commit hook in the readme is still valid?
there's no parameter "--baseline" in the help list of scan and audit and there's no scan or audit command mentioned in the git pre commit hook

**Comment by deknos** [comment]
(i am dkmbw, this is my private account).
i am currently reading your code and i realize that your pre-commit-hook is based on that python code and not on the main file. though i am still unsure if that's the case, you should point out that your pre_commit_hook and your 'normal binary call' from script or cli differ in that regard. 

but i'll try it later.

**Comment by domanchi** [comment]
Partially addressed in https://github.com/Yelp/detect-secrets/commit/b496b3a13320ddc0bbd05a0655edc8729be9f2a9
