### ISSUE TITLE
How to exclude some patterns from Base64HighEntropyString pattern 

### ISSUE THREAD

**Issue by ajaydell** [Yelp/detect-secrets#303]
Hi Team,

When i trying scan on my repo it is giving the output but those are not secrets in our code.
some the code lines are matching  Base64HighEntropyString plugin patterns how can i exclude those patterns or Base64HighEntropyString plugin . please help me  resolve the same

**Comment by KevinHock** [comment]
I wanna say we don’t have plugin specific —exclude-lines options, or file extension specific —exclude-lines options. 

PRs are welcome if the current option isn’t as flexible as needed 👍

**Comment by domanchi** [comment]
Yup, I agree with @KevinHock. You can also try using [inline whitelisting](https://github.com/Yelp/detect-secrets#inline-allowlisting), but depending on your file type, YMMV.
