### ISSUE TITLE
[bug] Catch requests.exceptions.RequestException in all plugins that verify secrets

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#306]
Currently when a `requests.whatever` in a `verify` function throws an exception, the code will land at https://github.com/Yelp/detect-secrets/blob/b496b3a13320ddc0bbd05a0655edc8729be9f2a9/detect_secrets/core/secrets_collection.py#L230-L231

We should instead wrap all `requests.whatever` calls in a `try: ... except requests.exceptions.RequestException: ...` so that we don't silently stop scanning an entire file. 

The "secret" that brought this up was an invalid one, so not necessarily a false-negative, but it is likely this will cause false-negatives.

Label: bug, good-first-issue

**Comment by domanchi** [comment]
This is addressed in https://github.com/Yelp/detect-secrets/pull/356/commits/badbcab10a83a8b1fcc2ead69769071f319c9efe
