### ISSUE TITLE
Add @KevinHock as external contributor

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#307]
_mostly so I can label GitHub issues, if that's okay_ 😄 

p.s. If not okay, I and others, still have PyPI access just fyi.

**Comment by OiCMudkips** [comment]
Hey, I've submitted a request to get you [Triage access](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization) but I'm not sure if we have prior art for this. I'll let you know if it goes through.

**Comment by KevinHock** [comment]
Thanks you very much @OiCMudkips  and @joshont1

**Comment by OiCMudkips** [comment]
Use your powers responsibly :)
