### ISSUE TITLE
[question] How to skip password detection in Windows .bat files

### ISSUE THREAD

**Issue by sylvainmouquet** [Yelp/detect-secrets#309]
Hello,

How to skip password detection in Windows .bat files

Thanks
Sylvain

**Comment by KevinHock** [comment]
You might have luck with the `--exclude-lines` regex, or the inline `pragma`. Do  you have info on which plugin is catching passwords or what the context looks like? i.e. An example file with a fake password.

**Comment by sylvainmouquet** [comment]
```batchfile
set PWD=%~dp0
rem echo %PWD%
"%PWD%\windows_9.6.6\pg_dump.exe" "--host" "cloud.google.com" "--port" "5432" "--username" "user" "--format=plain" "--schema-only" "--schema=public" "--file" "%PWD%src\sql\ref.sql" "ref"
pause
```

```
Location:    ./install/app/ref.bat:3
Secret Type: Hex High Entropy String
```

**Comment by OiCMudkips** [comment]
It looks like batch files has a `%= =%` syntax that we can abuse to put comments in the middle of lines (https://stackoverflow.com/a/12408045). You can put a `%= pragma: allowlist secret =%` at the end of line 3 to ignore that line in scanning.

Let us know if this works.

**Comment by OiCMudkips** [comment]
Feel free to re-open this issue if my proposed solution doesn't work.
