### ISSUE TITLE
private_key.py could be considered a derivative work without proper license attribution

### ISSUE THREAD

**Issue by asottile** [Yelp/detect-secrets#31]
https://github.com/Yelp/detect-secrets/blob/86e96ee9b90a6dbf3a66930b662bea4980624cee/detect_secrets/plugins/private_key.py#L20

https://github.com/pre-commit/pre-commit-hooks/blob/a193eab99ed99429b9b8e517be68bed9a7f6ec4f/LICENSE#L10-L11

Also noticed a few bugs in that file:

- [it only checks the first line of the file](https://github.com/Yelp/detect-secrets/blob/86e96ee9b90a6dbf3a66930b662bea4980624cee/detect_secrets/plugins/private_key.py#L37)
- [the copied code has drifted from the original source](https://github.com/pre-commit/pre-commit-hooks/blob/a193eab99ed99429b9b8e517be68bed9a7f6ec4f/pre_commit_hooks/detect_private_key.py#L6-L14)

**Comment by KevinHock** [comment]
Hi @asottile, sorry about that, it was an honest mistake on my part and @domanchi's, does https://github.com/Yelp/detect-secrets/pull/35 look okay to you?

**Comment by domanchi** [comment]
Fix merged.
