### ISSUE TITLE
Future Enhancment: filter potential secrets from baseline

### ISSUE THREAD

**Issue by dkmbw** [Yelp/detect-secrets#310]
Hey,
as i said, we have large and many repositories and we start cleaning them up. but we have also some blacklists of words which are NOT a secret. and we got an consent on example secrets which can be used for documentation issues, which shall not be regarded as secrets.

But of course, sometime we have to check that nobody really uses them as actual secrets in the git repository.

Therefore i would like to propose a `detect-secrets filter baseline.json` command which filters following stuff into a new baselinefile.json (via stdout as with scan), without

- certain files
- certain secret
- choosable combination of the above (must be both together, must be at least one of them..)

which we give the filter command via file, perhaps `--omit-files=...` or `--omit-potential-secrets=...`

That makes it easier to go over big repositories and test in them in a semi automated way.

**Comment by sharadpattanshetti** [comment]
This is really good feature to have it.

**Comment by OiCMudkips** [comment]
To exclude files, you can use either the `pre-commit` framework's `exclude` option, or if you're using this tool directly, the [`--exclude-files` flag](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/usage.py#L247-L254). This has to be done at scan time.

We also actually support the ignore-words option if you install this plugin using the [`word_list` extra](https://github.com/Yelp/detect-secrets/blob/master/setup.py#L26) and the [`--word-list` flag](https://github.com/Yelp/detect-secrets/blob/7776f4be3f1de476296d6fa754c730a41613ee6a/detect_secrets/core/usage.py#L19-L27).

Looking at our README we don't actually document these. We should definitely surface these features somewhere.

**Comment by dryoni** [comment]
I actually created an advanced audit tool decoupled from detect-secrets which reads baselines files and allows real time exclusion of line patterns and file patterns.
In addition, it aggregates all found secrets with same values so we can mark all of them as secrets or not secrets.
We've managed to audit ~9000 secrets in about 15 minutes.
This would be impossible to accomplish with the regular detect-secrets audit feature.
I actually pushed a new PR to support the advanced auditing tool (which requires having the secret length and position of the secret in line for each secret) - https://github.com/Yelp/detect-secrets/pull/332
Hope it will be approved, and I'll publish my auditing tool, and help integrate it into detect-secrets

![image](https://user-images.githubusercontent.com/20098914/90309875-00ccd880-def5-11ea-98c2-2c355bcdab16.png)

**Comment by domanchi** [comment]
In the upcoming v1 version (currently residing in `pre-v1-launch` branch), we introduce the concept of filters: https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/filters.md. This might address your needs.

If you wanted to extract the list of secrets from this filter, you probably can run two rounds: one with the filter, and one without, then use the `audit --diff` functionality to compare them.

@dryoni : I would be very interested to learn more about your additions to speed up the audit process! I'm going to close this issue though, as your feature is only tangentially related to the original question asked.
