### ISSUE TITLE
Can I get the file_content ?

### ISSUE THREAD

**Issue by opt9** [Yelp/detect-secrets#318]
Technically speaking, It seems that detect-secrets get the file_contents from the git repo and check it. I want to get the file_contents in the relevant line and store it to the db. Does detect-secrets provide the option to return that data?

**Comment by OiCMudkips** [comment]
Can you explain your use-case? Can you use existing values from a secrets baseline?

**Comment by gitmopp** [comment]
I think the questions goes in this direction.
When you run the scan the result is:
`    "myfile": [
      {
        "hashed_secret": "d5edfbd14a2382e5a8bd1234567ae12345678901",
        "is_verified": false,
        "line_number": 5,
        "type": "Basic Auth Credentials"
      }
`
It would be nice to see what was found, e.g.
`    "myfile": [
      {
        "hashed_secret": "d5edfbd14a2382e5a8bd1234567ae12345678901",
        "found": http_proxy=http://user:password123@myproxy:8080
        "is_verified": false,
        "line_number": 5,
        "type": "Basic Auth Credentials"
      }
`

**Comment by domanchi** [comment]
No. Baselines were not designed to have original secrets in them, since we did not want to have a single file with all the secrets in them. You may be able to experiment with `detect-secrets audit --display-results`, but that API will probably change in v1 so YMMV.
