### ISSUE TITLE
Can I create an "allow list" of safe text?

### ISSUE THREAD

**Issue by aaronsteers** [Yelp/detect-secrets#334]
I create sample projects where I frequently need to do something like:

`creds-file-template.txt`
```
user     = your-username-here
password = your-password-here
```

and I would like to create an exception "if you would otherwise alarm on this line related to the text `your-password-here`, skip it instead because that's not a real password.

Is there any way to do this besides pasting a comment on each line?

**Comment by KevinHock** [comment]
Check out the `--exclude-lines` feature, it should exclude any lines matching the regex 👍🏼

**Comment by KevinHock** [comment]
Let me know if that didn't answer your Q, closing this otherwise 👍🏼

**Comment by aaronsteers** [comment]
It did! Thank you! But I don't see much in terms of docs or examples. Would you mind if we keep this open for a bit to expand the docs?

If I'm not overlooking anything, and if you think adding an example or two sounds good to you also, I'm happy to create a PR to add a section into the docs. Just let me know if this would go in the main readme or in another location...

Totally fine either way. Appreciate your help.

**Comment by KevinHock** [comment]
A PR would be very much appreciated @aaronsteers :)

**Comment by mikkelblanne** [comment]
As a tip, you could also avoid having to add additional configuration by using one of the existing false positive keywords, like "secret": https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/keyword.py#L50

**Comment by domanchi** [comment]
Will add this to the README in v1. Re-closing.

**Comment by aaronsteers** [comment]
@mikkelblanne - The 'false positives' list looks like exactly what I was looking for. If I understand this correctly, I can use something in the list, like `thisisnotasecret` or `dummy_secret`, instead of using my own dummy value and then adding it to an allow list.

@domanchi - I didn't see the false positive list in the docs, but that would be a great addition if I understand it correct.

**Comment by mikkelblanne** [comment]
Exactly. I'm trying to get people to start using `dummy_secret` - if it's the same everywhere, we avoid wasting time trying to figure out whether somebody else's dummy value is actually a real secret.

**Comment by domanchi** [comment]
@aaronsteers : see if this helps: https://github.com/Yelp/detect-secrets/tree/pre-v1-launch#filters. NOTE: `filters` is a concept introduced in v1.0, which 🤞 will go out soon.

**Comment by aaronsteers** [comment]
@domanchi - Absolutely, yes. This does address my original request which was dynamic "word allowing". 

That said, is there also a doc section around the built-in "false positive" as @mikkelblanne notes above?

> As a tip, you could also avoid having to add additional configuration by using one of the existing false positive keywords, like "secret": https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/keyword.py#L50

To be clear, there are many items on that list we probably don't need to document, but perhaps a section that gives 2-5 of the most useful (most best practice?) options so people can get similar behavior even without introducing extra CLI args.

**Comment by aaronsteers** [comment]
@domanchi - I'm just spitballing here but what about inserting the below right before the [inline allowlisting](https://github.com/Yelp/detect-secrets/tree/pre-v1-launch#inline-allowlisting-1) section?

--------------------------

## Automatically-ignored values

When writing boilerplate code or readme files, it is often useful to use one a predefined list of sample values. The following keywords are automatically identified by `detect-secrets` as false positives, and will be ignored by default from secrets detection.

* `dummy_secret`
* `dummy_value`
* `thisisnottherealsecret`


--------------------------

Alternatively: this could be an extension to the [`--word-list`](https://github.com/Yelp/detect-secrets/tree/pre-v1-launch#--word-list) section.... 

--------------------------

#### --word-list

If you know there are certain fake password values that you want to ignore, you can also use this option:

```
$ cat wordlist.txt
not-a-real-secret
$ detect-secrets scan --word-list wordlist.txt
```

By default, the following build-in words are always ignored:

* `dummy_secret`
* `dummy_value`
* `thisisnottherealsecret`

--------------------------

What I like about putting it inline with the word list, is that if a users' use case allows it, we may encourage them to use the default ignored words rather than creating their own list.

**Comment by prathamesh199728** [comment]
can we suppress pem keys in wordlist? Its giving error when I was trying
