### ISSUE TITLE
Tag version 0.14.3 in GitHub

### ISSUE THREAD

**Issue by nymous** [Yelp/detect-secrets#339]
Version 0.14.3 is available on PyPI, but it isn't tagged on GitHub.
As such using the pre-commit hook with `rev: v0.14.3` doesn't work.

Could you please tag it since it has been released? Thanks!

**Comment by OiCMudkips** [comment]
Whoops, done.

**Comment by KevinHock** [comment]
Ahh, bumpity doesn't do this https://github.com/Yelp/detect-secrets/blob/master/scripts/bumpity.py, maybe it should
