### ISSUE TITLE
general question- detect-secrets as plugin to vscode or intellij?

### ISSUE THREAD

**Issue by holyender** [Yelp/detect-secrets#341]
hey all!
Ive been working on developing a system that prevents devs from committing secrets to bitbucket. so far i got the precommit hook and detect secrets working on terminal. But i realized a lot of devs use git gui or a git plugin in their IDE to commit code. has anyone had any experience working with that? how did it go? did you have to use a hacky way? is there a plugin for detect-secrets for vscode etc? 
any suggestions would be appreciated.
also is there a slack channel for this community or related communities?

**Comment by domanchi** [comment]
Hi @holyender , there is currently no slack channel (because we couldn't figure out how to support open invites for anyone). `detect-secrets` for vscode does sound interesting! If you do explore that idea, let us know how it goes!
