### ISSUE TITLE
Fix compatibility issue with detect-secrets-server after introduction of "---custom-plugins"

### ISSUE THREAD

**Issue by francisluz** [Yelp/detect-secrets#343]
#### 🗒️  Description

As `detect-secrets-server` doesn't support the flag `--custom-plugins` it's casing an error when you try to run the server with the latest client version.

#### 🐛 Bug Report

This bug has been reported at `detect-secrets-server` [62](https://github.com/Yelp/detect-secrets-server/issues/62)

#### 💡 Solution

Some code check need to be done when you're using the argument `custom_plugin_paths` and when you try to delete an attribute that is not present in collection.

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
