### ISSUE TITLE
docker-sercrets scan command runs infinitely in ubuntu container

### ISSUE THREAD

**Issue by ramshankar000** [Yelp/detect-secrets#348]
After I have installed the the detect secret Version: 0.14.3 i am trying to run detect-secrets scan command in container but unfortunately it runs infinitely in project root directory. Am I missing something here ?

**Comment by domanchi** [comment]
@ramshankar000 , try running it with the verbose flags on `-vvv`. This will often give you a good start for debugging. If you are still stuck, please provide some output from this that our team can look at to investigate.

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
