### ISSUE TITLE
v0.14.3 not marked as the "Latest release" within GitHub

### ISSUE THREAD

**Issue by denizgenc** [Yelp/detect-secrets#349]
See https://github.com/Yelp/detect-secrets/releases - v0.14.3 is available, but v0.14.2 is marked as the latest (https://github.com/Yelp/detect-secrets/releases/latest)

This isn't a huge problem, but it caused me a bit of concern when I ran `pip install -U detect-secrets` and got a version newer than on the GitHub home page! (It also makes it a tiny bit harder when trying to find the tagged commit to use for my pre-commit-config.yaml file.)

**Comment by OiCMudkips** [comment]
Fixed, thanks!
