### ISSUE TITLE
baselines break with version bumps

### ISSUE THREAD

**Issue by domanchi** [Yelp/detect-secrets#37]
Currently, baselines have no notion of which version of detect-secrets created it. This makes things slightly annoying, because with a major version bump, it could invalidate old baselines, requiring the user to recreate the baseline to be compliant once again.

At the very least, we should have baselines know which detect-secrets version created it, so we can be aware when this happens.

**Comment by KevinHock** [comment]
0.8.2 are one version, 0.8.8 is a new, breaking version. Due to `detect-secrets` thinking the secrets that have the same hash but different types are different. (https://github.com/Yelp/detect-secrets/pull/26/files was the change you will notice if you update to 0.8.8)

**Comment by KevinHock** [comment]
Note: If we don't update/change the plugin version types in the future, this is relatively preventable IMO

**Comment by KevinHock** [comment]
A related aside: I didn't update the CHANGELOG when I bumped, in a rush. Feel free to not approve my next PR until I do so. ([May add emojis](https://github.com/python-security/pyt/blob/master/CHANGELOG.md)
