### ISSUE TITLE
keyword plugin can hang on very long lines

### ISSUE THREAD

**Issue by gpflaum** [Yelp/detect-secrets#372]
Scanning a very long line causes a hang at denylist_regex.search(string) in keyword.py for the FOLLOWED_BY_QUOTES_AND_SEMICOLON_REGEX regex.

The attached file [VeryLongLine.zip](https://github.com/Yelp/detect-secrets/files/5587539/VeryLongLine.zip) has a 100,000 character line and hangs for at least 15 minutes before I kill it. That file is derived from a real source file.

I'll make a PR for the pre-v1-launch branch. The problem also happens with the master branch.

**Comment by jpdakran** [comment]
This has been fixed with #373. I tested the above file and this runs in 0:00.42.  I will consider this resolved. If you have any other questions or you do not consider this resolved - please re-open an issue and the team will be happy to assist. Thanks!
