### ISSUE TITLE
[question] How to whitelist secret in the cshtml?

### ISSUE THREAD

**Issue by DariuszPorowski** [Yelp/detect-secrets#378]
Hi

I have example code like below inside .cshtml file (C# HTML webpage file used by Razor)
```
                    <p>
                        User: <b>demouser@domain.com</b>
                    </p>
                    <p>
                        Password: <b>Pass@word1</b>
                    </p>
```
and I have to whitelist Pass@word1. I tried HTML comment style and Razor as well.

`<!-- pragma: allowlist secret -->`
`@* pragma: allowlist secret *@`

Both do not work, and always got this:

```
"Login.cshtml": [
      {
        "hashed_secret": "9a02ee9d59b6c90326a66b2a577c43a74e7091b5",
        "is_verified": false,
        "line_number": 53,
        "type": "Secret Keyword"
      }
    ]

```
Any ideas? Thanks! :)

**Comment by lgmorand** [comment]
@DariuszPorowski that's funny, I have the same kind of need for my OH ;-)

**Comment by DariuszPorowski** [comment]
Got the solution:
`@* # pragma: allowlist secret *@`

Adding `#` before pragma works :)
