### ISSUE TITLE
Security Slack Channel should be a parameter

### ISSUE THREAD

**Issue by sfc-gh-nsfard** [Yelp/detect-secrets#406]
one of the mitigation suggestions that are printed when detect-secrets fails a scan states:

```
- For information about putting your secrets in a safer place,
    please ask in #security
```

This is a bit confusing for developers since we don't have a #security channel and we wouldn't use that channel for this type of question anyway. I think this should be a custom value that's handled as a commandline parameter (or via a config file or an environment variable)

I notice it's currently being hardcoded here: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/pre_commit_hook.py#L210

I also notice there that `DETECT_SECRETS_SECURITY_TEAM` is already an environment variable we can set. I think it'd be pretty easy to just create another env var called `DETECT_SECRETS_SLACK_CHANNEL` with `#security` being the default value. What do you think?

**Comment by domanchi** [comment]
Pull requests welcome.

**Comment by sfc-gh-nsfard** [comment]
@domanchi PR here: https://github.com/Yelp/detect-secrets/pull/413

**Comment by BlueCanary-DM** [comment]
You can also trigger a slackbot via email.

**Comment by domanchi** [comment]
From the linked PR, it looks like this functionality is already supported. i.e. you can do

```
DETECT_SECRETS_SECURITY_TEAM='in #blah' detect-secrets scan ...
```

which will result in:

```
For information about putting your secrets in a safer place, please ask in #blah.
```
