### ISSUE TITLE
Bug auditing test_data/config.yaml with binary values

### ISSUE THREAD

**Issue by pablosantiagolopez** [Yelp/detect-secrets#421]
We found the following bug scanning detect-secrets project when the file `test_data/config.yaml` is audited:

![bug_audit](https://user-images.githubusercontent.com/69458381/110467963-ef892a80-80d7-11eb-863f-55fa65e74f41.png)

We tried to solve this bug in #414, and we get it in the most cases, but this file includes the following line: `low_entropy_binary_secret: !!binary MjNjcnh1IDJieXJpdXYyeXJpaTJidnl1MnI4OXkyb3UwMg==`. We try to parse this file as YAML from python and we get the following behaviour:

<img width="623" alt="bug_config_yaml" src="https://user-images.githubusercontent.com/69458381/110468333-6e7e6300-80d8-11eb-8774-67a53a879005.png">

As can you see, the secret value changes when the file is parsed as YAML, so I think that this bug can be introduced by the YAML transformer. I'm not sure because I don't know how this transformer works exactly. 

I also think that this bug is due to the specific value included in this file and it isn't a generic problem. I don't know how to fix it, so I open this issue to report it.

**Comment by domanchi** [comment]
Hmm. I'm unable to reproduce this. Can you provide a minimal YAML file that causes this issue on `master`?

Cases I've tried:
- `low_entropy_binary_string` in YAML file by itself
- `low_entropy_binary_string` in YAML file, preceded by a new line
- `low_entropy_binary_string` in YAML file, preceded by an arbitrary key pair
- `low_entropy_binary_string` in YAML file, preceded by a secret
- `low_entropy_binary_string` in YAML file, preceded by an arbitrary key pair + secret and a new line

They all have varying results (raising other issues), but none that raises this traceback that you provided.

**Comment by pablosantiagolopez** [comment]
Yes of course, the YAML file that causes this issue is [this](https://github.com/Yelp/detect-secrets/blob/master/test_data/config.yaml). Can you reproduce this?

**Comment by domanchi** [comment]
Oh goodie. This means we have good test cases. But the fact we didn't catch it in our test cases means we're missing something lol.

I was able to reproduce with this file. I'll check it out.

**Comment by pablosantiagolopez** [comment]
Thank you very much @domanchi !!
