### ISSUE TITLE
False Positives Scan

### ISSUE THREAD

**Issue by rafaelsilvaa10** [Yelp/detect-secrets#426]
Hello, i am using the detect-secrets in my cicd. 

I use the command on the repo folder:    
`"detect-secrets scan . "`

and it works, but it contains some false positives, for example:

```
   ],
   "config/index.js":[
      {
         "type":"Secret Keyword",
         "filename":"config/index.js",
         "hashed_secret":"398ec9c29cf195ff9202bd85b75002adc88832c3",
         "is_verified":false,
         "line_number":12
      
```

in that line of the file, it contains :
```
const configObject = _.merge({}, defaults, config, {
  **db: { password: '*******' },**
});
```

I believe he found the word "**password**" and alarmed.

How do you solve this kind of thing? 
I understand that it is to alarm, however there are some cases but in other cases when the value is not explicit for example ***** or a **/parameter/aws/key/**  should not be alarmed

I have other scenarios than the value of the variable `passowrd = "/ parameters/store_of_aws/key"
`

So I believe that basically I need to put it on the whitelist every time I find it
/ parameterStore on the line
and **** too

Thank you for your help.

**Comment by domanchi** [comment]
@rafaelsilvaa10 , you can use [custom filters](https://github.com/Yelp/detect-secrets/blob/master/docs/filters.md#using-your-own-filters) to handle cases like this.

Alternatively, when the next version comes out, you can try using the [gibberish detector](https://github.com/Yelp/detect-secrets#gibberish-detector) -- an ML based solution that attempts to ignore secrets that aren't gibberish (i.e. `parameterStore`).

**Comment by rafaelsilvaa10** [comment]
Great, thank for reply.

Its works for me using regex in ignore-lines parameter.

**Comment by domanchi** [comment]
That certainly one way to do it. In our experience, regex based whitelists are good -- until they become unwieldy, making you wish you had a programmatic method to tune your filters. If that situation happens to you, you can be assured that `detect-secrets` has that built-in feature to support that use case.
