### ISSUE TITLE
How to set timeout in my scanner? 

### ISSUE THREAD

**Issue by rafaelsilvaa10** [Yelp/detect-secrets#433]
hello, 

I'm having problems scanning a repository, it's taking too long.

`detect-secrets scan . --exclude-lines .*: parameterSecurity:/.* --exclude-lines .*: parameter:/.* --exclude-files=package-lock.json`

there are scans that are taking 10hrs another 1min ... is it due to the regexp?

However is there any parameter --timeout in the cli?

thanks

**Comment by domanchi** [comment]
What version are you running?

**Comment by rafaelsilvaa10** [comment]
1.0.3

**Comment by domanchi** [comment]
Probably the best way to debug whether it's a specific file is by doing chunks at a time, and enabling debug logs with `-vv`. I know there's a performance issue on `master`, but fixes are ready to be merged, and will go out in the next minor version bump.

If you're not running on `master`, do let us know if you find the performance issue, and we may be able to improve it for others.

**Comment by jpdakran** [comment]
@AIGeneratedUsername To scan in verbose mode try `detect-secrets -vv scan`

**Comment by lorenzodb1** [comment]
We’re going to close this issue as it hasn’t received any update in a very long time. Feel free to re-open it if you think it’s still relevant.
