### ISSUE TITLE
Do not report git SHAs as secrets

### ISSUE THREAD

**Issue by holyjak** [Yelp/detect-secrets#437]
Hello! Thank you for this great tool!

I have a few files that refer to git SHAs and detect-secrets complains about these:

```
Secret Type: Hex High Entropy String
Location:    .clojure/deps.edn:77
```

where the source file contains

```clojure
:sha "9ccf64be248d5d9aa641df9e94feaea913bc0687"
```

I guess, give how common git and referring to concrete git hashes it, they should either be recognized as non-secrets or there should be a simple way to ignore them.

**Comment by domanchi** [comment]
@holyjak, the issue about SHAs is that real secrets can also be SHAs. As such, `detect-secrets` does not ignore them by default; rather, it provides functionality that you can use to easily customize your own filters.

Check out https://github.com/Yelp/detect-secrets/blob/master/docs/filters.md#using-your-own-filters for more details.

**Comment by holyjak** [comment]
Thanks a lot, @domanchi ! That makes perfect sense.

Could you be so very kind and tell me why this does not work:

```python
# .detect-secrets-filter-git-sha.py
def not_deps_git_sha(filename: str, line: str, secret: str) -> bool:
    print("not_deps_git_sha: '" + filename + "' =>" + (filename == "deps.edn" and ":sha" in line))
    return not (filename == "deps.edn" and ":sha" in line)
```

even when I run `detect-secrets scan --filter ./.detect-secrets-filter-git-sha.py::not_deps_git_sha .clojure/deps.edn` the same git sha are reported as secrets. My filter is in the list of filters used but I never see the output of its `print` so it seems not to be invoked?

**Comment by domanchi** [comment]
What does running `detect-secrets` in debug mode (`-vv`) give you?

**Comment by holyjak** [comment]
Nothing, really, just a single extra line, `[scan]	INFO	Checking file: .clojure/deps.edn`

**Comment by holyjak** [comment]
🙏 @domanchi have you any more tips how to troubleshoot this and get the filter working?

**Comment by domanchi** [comment]
Filters need to return `True` if the secret should be skipped. I think you have your boolean logic inverted.

**Comment by holyjak** [comment]
Thank you but that did not help. And the `print` in my filter fn is not printing (at least not to stdout) so it does not seem to be called at all. Are there some filter troubleshooting guidelines? Why would my filter not be called?

**Comment by domanchi** [comment]
I can't help you much, because I was unable to reproduce this on my machine.

```bash
$ pip install detect-secrets
$ detect-secrets --version
1.0.3

$ cat blah
:sha "9ccf64be248d5d9aa641df9e94feaea913bc0687"
$ detect-secrets scan blah | jq .results
{
    "blah": [
        {
            "filename": "blah",
            "hashed_secret": "6c9c450a6692ebc60ea691bae6e064262a63bab8",
            "is_verified": false,
            "line_number": 1,
            "type": "Hex High Entropy String"
        }
    ]
}

$ cat blah_filter.py
def not_deps_git_sha(filename: str, line: str, secret: str) -> bool:
    return ":sha" in line
$ detect-secrets scan --filter ./blah_filter.py::not_deps_git_sha blah
{
  "version": "1.0.3",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "Base64HighEntropyString",
      "limit": 4.5
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "HexHighEntropyString",
      "limit": 3.0
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    },
    {
      "path": "detect_secrets.filters.heuristic.is_indirect_reference"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_templated_secret"
    },
    {
      "path": "file://./blah_filter.py::not_deps_git_sha"
    }
  ],
  "results": {},
  "generated_at": "2021-03-27T14:16:36Z"
}
```

Also note that the custom filter is added to the generated baseline.

**Comment by holyjak** [comment]
Thanks a lot, @domanchi! I had a `print` call before the r`return` in my function and it somehow made it non functional. After removing the line it work as intended.

**Comment by holyjak** [comment]
(I was also confused by the argument name `filename`, which turned out to be actually a file path so my check for `==` did not work.)
