### ISSUE TITLE
Docker digests are found as a secret

### ISSUE THREAD

**Issue by jeff-cook** [Yelp/detect-secrets#443]
Finding a number of false positives with Docker image digest hashes.

How to configure to avoid this issue? 

```
Secret:      1 of 1
Filename:   Dockerfile
Secret Type: Hex High Entropy String
----------
1:FROM alpine@sha256:ec14c7992a97fc11425907e908340c6c3d6ff602f5f13d899e6b7027c9b4133a
----------
```

**Comment by domanchi** [comment]
Try writing your own filter: https://github.com/Yelp/detect-secrets/blob/master/docs/filters.md#writing-your-own-filter
