### ISSUE TITLE
detect-secrets v1.1.0 fails to load any plugins on py38

### ISSUE THREAD

**Issue by aristotelesneto** [Yelp/detect-secrets#452]
For some reason on my MacOS (Big Sur, pyenv, python 3.8.8 / 3.9.4) detect-secrets 1.1.0 fails to detect any secret, whereas 1.0.3 seems to work fine.

When using detect-secrets scan with 1.1.0 it returns:
```
% detect-secrets --version              
1.1.0
% detect-secrets scan
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
[scan]  ERROR   No plugins to scan with!
{
  "version": "1.1.0",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "Base64HighEntropyString",
      "limit": 4.5
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "HexHighEntropyString",
      "limit": 3.0
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    },
    {
      "path": "detect_secrets.filters.heuristic.is_indirect_reference"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_lock_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_not_alphanumeric_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_swagger_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_templated_secret"
    }
  ],
  "results": {},
  "generated_at": "2021-04-16T00:24:54Z"
}

% detect-secrets scan --list-all-plugins
ArtifactoryDetector
AWSKeyDetector
AzureStorageKeyDetector
BasicAuthDetector
CloudantDetector
Base64HighEntropyString
HexHighEntropyString
IbmCloudIamDetector
IbmCosHmacDetector
JwtTokenDetector
KeywordDetector
MailchimpDetector
NpmDetector
PrivateKeyDetector
SlackDetector
SoftlayerDetector
SquareOAuthDetector
StripeDetector
TwilioKeyDetector
```

If I switch to Python 3.7.9 (or revert back to 1.0.3) it seems to work correctly.

```
% detect-secrets --version         
1.0.3
% detect-secrets scan     
{
  "version": "1.0.3",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "Base64HighEntropyString",
      "limit": 4.5
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "HexHighEntropyString",
      "limit": 3.0
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    },
    {
      "path": "detect_secrets.filters.heuristic.is_indirect_reference"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_templated_secret"
    }
  ],
  "results": {
    "tests/conftest.py": [
      {
        "type": "Secret Keyword",
        "filename": "tests/conftest.py",
        "hashed_secret": "dc724af18fbdd4e59189f5fe768a5f8311527050",
        "is_verified": false,
        "line_number": 50
      }
    ]
  },
  "generated_at": "2021-04-16T00:26:42Z"
}

% detect-secrets scan --list-all-plugins
ArtifactoryDetector
AWSKeyDetector
AzureStorageKeyDetector
BasicAuthDetector
CloudantDetector
Base64HighEntropyString
HexHighEntropyString
IbmCloudIamDetector
IbmCosHmacDetector
JwtTokenDetector
KeywordDetector
MailchimpDetector
NpmDetector
PrivateKeyDetector
SlackDetector
SoftlayerDetector
SquareOAuthDetector
StripeDetector
```

**Comment by domanchi** [comment]
Super interesting problem.

I took a quick look, and it turns out that the issue is with the changes that Python3.8 introduced to the `multiprocessing` library. I hypothesize that Python3.8 doesn't share memory between processors by default, which means that the global settings object becomes inaccessible across processors: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/secrets_collection.py#L58-L64

If you downgrade to Python3.7, you should be able to run this on v1.1.

**Comment by aristotelesneto** [comment]
I can confirm running on v1.1 works correctly on python 3.7.9. Interestingly, on an Azure DevOps pipeline running Python 3.8 (ubuntu-latest [20.04] agent, ms hosted) detect-secrets v1.1 correctly finds secrets (but because we couldn't baseline it, it meant it was failing our build). Is there some more data you'd like me to capture myself to be able address this issue or were you able to reproduce?

**Comment by domanchi** [comment]
Weeird.

I was able to reproduce this on MacOS Catalina, pyenv, 3.8.5. And if my hypothesis is correct, you won't encounter this issue if you try scanning **one** file, since I wrote a bypass for that case: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/secrets_collection.py#L51-L53.

Could you verify that?

**Comment by s1mrankaur** [comment]
getting the same issue on windows 10

**Comment by YustinS** [comment]
To add to this, can confirm the same behavior on Windows 10 using Python 3.7.9.
![image](https://user-images.githubusercontent.com/9688705/115320323-c5964e00-a1d5-11eb-9e20-d328a68b6150.png)

As mentioned above scanning an individual file completes successfully and returns good results, as well as downgrading to version 1.0.3 doesn't have the issue

**Comment by DenysVuika** [comment]
Spent lot of time on this issue before coming across this ticket... downgrading to 1.0.3. works for me

**Comment by shadawck** [comment]
It happens to me programmatically with the pypi package. 
When using solely `scan_file()` like below I get  `"[scan] ERROR No plugins to scan with!"` :
```python
...
for file in files:
    secrets.scan_file(file)
...
```

But when using with default_settings() everything works fine : 
```python
...
with default_settings():
    for file in files:
        secrets.scan_file(file)
...
```

`default setting()` enables all filters and plugins by default. So I can suggest to enable all plugins on the command line:
```sh
> detect-secrets scan --force-use-all-plugins
```

PS: I have not tested the cli solution.

Versions used : 
```sh
> python3 --version
Python 3.8.6
> detect-secrets --version
1.1.0
```

**Comment by edthedev** [comment]
Same problem on Windows.

```
> python -V
Python 3.8.0
> detect-secrets --version
1.1.0
```

**Comment by gpflaum** [comment]
@domanchi wrote:
> I was able to reproduce this on MacOS Catalina, pyenv, 3.8.5. And if my hypothesis is correct, you won't encounter this issue if you try scanning one file, since I wrote a bypass for that case: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/secrets_collection.py#L51-L53.
>
> Could you verify that?

Verified. Scanning a folder with `python -m detect_secrets scan test_data` with Python 3.8 gets the "No plugins to scan with!" error, while scanning a single file with `python -m detect_secrets scan test_data/config.ini` works.

**Comment by gpflaum** [comment]
@shadawck suggested trying `--force-use-all-plugins`. That didn't work, still get the "No plugins to scan with!" error.

**Comment by agemooij** [comment]
> @domanchi wrote:
> 
> > I was able to reproduce this on MacOS Catalina, pyenv, 3.8.5. And if my hypothesis is correct, you won't encounter this issue if you try scanning one file, since I wrote a bypass for that case: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/secrets_collection.py#L51-L53.
> > Could you verify that?
> 
> Verified. Scanning a folder with `python -m detect_secrets scan test_data` with Python 3.8 gets the "No plugins to scan with!" error, while scanning a single file with `python -m detect_secrets scan test_data/config.ini` works.

Same here using v1.1.0 installed through homebrew on MacOS with `python3 --version` at `3.9.7`. 
Scanning the individual file was successful while all other run modes I tried fail.

**Comment by wbreza** [comment]
Any update on this feature? I'd like to leverage the latest features in v1.1.0 but this is a blocking issue for me.  Able to repro on Windows 10/11 with Python 3.7+

**Comment by edthedev** [comment]
I'm also willing to help test when this is resolved, as I believe I still have an organizational 'how-to' document that has a pinned version that I would love to see removed.
