### ISSUE TITLE
Spurious “Nothing to audit!” in v1.1.0

### ISSUE THREAD

**Issue by acdha** [Yelp/detect-secrets#456]
I ran into an interesting failure with v1.1.0. I've already had to back that update out due to #452 but it looks like it also fails to handle auditing an existing secrets baseline file.  I was using the pre-commit hook with v1.1.0 and it'd fail like this:

```
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1

ERROR: Potential secrets about to be committed to git repo!

Secret Type: Base64 High Entropy String
…
```

Looking at the baseline file would show a number of entries like this:

```json
"is_verified": false,
"line_number": 4,
"is_secret": false
```

But if I ran `audit` to review them, it would insist there was nothing to audit:

```bash
$ detect-secrets audit .secrets.baseline
Nothing to audit!
```

**Comment by jpdakran** [comment]
@acdha Hello. Can you please retry this in v1.3.0?
