### ISSUE TITLE
What's the future of detect-secrets?

### ISSUE THREAD

**Issue by gpflaum** [Yelp/detect-secrets#473]
@domanchi and @KevinHock left Yelp in April. Is anyone at Yelp taking over leadership of this project?

@killuazhu Is IBM's fork at https://github.com/IBM/detect-secrets suitable for people to use, or is it too customized for use at IBM?

**Comment by gpflaum** [comment]
Looks like IBM's fork hasn't pulled in the big changes from the [v1.1.0](https://github.com/Yelp/detect-secrets/releases/tag/v1.1.0) release.

**Comment by justineyster** [comment]
@gpflaum Hey! We should definitely pair on this. We are definitely still maintaining the project within IBM. Our process for pulling in upstream changes has gotten pretty hefty, thus why we haven't done it lately, but we're planning to revisit/revise that process soon.

**Comment by justineyster** [comment]
> Is IBM's fork at https://github.com/IBM/detect-secrets suitable for people to use, or is it too customized for use at IBM?

Our fork should be suitable for anyone to use.

**Comment by rossgrady** [comment]
We definitely have work in plan for the 2nd half of the year to pull in the big changes, but as Justin said, they're big changes :)

The rebase is gonna **hurt** for a minute or three but we still plan to attack it.

**Comment by gpflaum** [comment]
@justineyster @rossgrady Thanks for the response. I'm not currently using detect-secrets, but did some work with it several months ago and was going to resume using it soon, but noticed domanchi had left. I can't contribute much to development of detect-secrets but can probably help with testing. We'll see if there's any reply from Yelp, but IBM might be the most actively maintained fork.

**Comment by domanchi** [comment]
@gpflaum : unfortunately, having left the company, I no longer have merge access and therefore, it would be redundant for me to review incoming PRs. During the last couple of months at Yelp, the team was struggling with bandwidth (with me being a sole maintainer of this), so I'm not surprised that this library fell through the cracks with my departure.

@rossgrady : I definitely agree the rebase will probably be painful, but FWIW, I'm happy to review those PRs if you think it will be useful. I think this tool is pretty beneficial to the community, and it would be a shame if it was left unattended.

**Comment by KevinHock** [comment]
Hi @domanchi , I still have merge access, super happy to merge any PRs you approve. 👍🏼 

I'll go through the open PRs and see what I can review as well, I don't have much bandwidth to fix issues however, unfortunately.

**Comment by domanchi** [comment]
@KevinHock : while I appreciate the offer, I still think it's a pretty flimsy band-aid fix. I think we've attempted to do this during the great refactor for launching v1, and that didn't turn out so well.

Let me try to poke Yelp for a response on this through out-of-band channels.

**Comment by KevinHock** [comment]
I agree, thanks @domanchi!

(An aside for this thread, Pinterest uses detect-secrets, but I don't do AppSec anymore so I have less work related reasons to maintain/contribute unfortunately.)

**Comment by justineyster** [comment]
Update from the IBM side. I'm going to explore rebasing our fork to pick up the v1.1.0 changes tomorrow. 🙂

**Comment by justineyster** [comment]
After exploring this today, I've come to realize that the two forks have diverged too much over the past year for our [old rebase process](https://github.com/IBM/detect-secrets/blob/master/update.md#how-do-we-keep-update-to-date-with-upstream) to be even remotely feasible. We're going to switch gears towards individually cherry-picking new features from this fork into our own.

**Comment by rossgrady** [comment]
Like @KevinHock I'd like to apologize for the lack of comms from the IBM side -- we spent the year heavily focused on things like the Kyndryl spinoff (and then catching up on all the work that had been deferred by focusing on the Kyndryl spinoff).

We are now leaning back towards the opinion that rebasing on the 1.x re-architecture would be worth our time (it was a good re-architecture! Just gonna be challenging . . .)

We are also prepared to do whatever Kevin thinks is most beneficial to the community, whether it's simply pointing ppl to our fork from here, giving us committer access on this project, or any other option in between.

**Comment by domanchi** [comment]
@rossgrady , if it helps, I would be open to having a conversation to better understand IBM's modifications, in order to brainstorm approaches for performing the migration. I've attempted to contact Yelp multiple times but have not heard back. Given this lack of official response, I can only conclude that this tool is probably (inadvertently) EOL.

Given that maintainers are a requirement for a healthy package (and that I have been locked out of this one), if IBM intends to continue maintaining it, the community might need to pivot over. However, the new 1.X architecture did solve many problems that we discovered during internal development -- it would be optimal to port it over to a new official fork/port, if it came to that.

There will also probably be complications with ownership of the package namespace, but for the sake of the community (and continued development of this tool), this might be the best option.

**Comment by killuazhu** [comment]
> 1.x

If IBM wants to keep sustaining the project with 1.x changes, we would need to
1. revisit the [rebase attempt](https://github.com/Yelp/detect-secrets/issues/473#issuecomment-888562855) @justineyster did earlier on
2. resolve #452 since Python 3.8 is not dying any time sooner.

**Comment by rossgrady** [comment]
@domanchi @KevinHock Would y'all be open to meeting with our team in the week of January 10th to talk about all of the things Aaron mentions here? https://github.com/Yelp/detect-secrets/issues/473#issuecomment-987508529

We intend to continue contributing, we do think that rebasing on 1.x is the path forward, and we're open to whatever makes the most sense for the health of the project & the community. So hopefully it'll be a fun & easy meeting :)

**Comment by domanchi** [comment]
@rossgrady : SGTM. I'll shoot you an email with my contact information, and we can set something up.
@killuazhu : I recently saw a [promising PR](https://github.com/Yelp/detect-secrets/pull/482) that actually fixes that known issue.

**Comment by KevinHock** [comment]
Hi @calvinli and @jpdakran,

Would it be alright if we moved detect-secrets to a separate GitHub organization? (e.g. https://github.com/detect-secrets-oss -- I just made that and I am agnostic to the name).

This way we could add folks from e.g. IBM and give them write access. As well as have a place to store the menagerie of separate but related detect-secrets repositories from IBM [[1](https://github.com/IBM/detect-secrets-stream)], Microsoft [[2](https://github.com/wbreza/baseline-security-seed), [3](https://github.com/wbreza/pre-commit-hooks/tree/main/detect-secrets)] and others.

p.s. I've invited you both as admins, along with @domanchi.

*I realize you'll have to run this by Yelp folks internally, and that will take time.* Feel free let me know how this goes privately via e-mail if you'd prefer. (There is a lot of precedence for this, such as [pre-commit](https://github.com/pre-commit), made at Yelp. And industry-wide, such as https://github.com/envoyproxy/envoy), made at Lyft.

The biggest benefit I see from this is that the repository will be more resilient at staying active/maintained for long periods of time.

**Comment by calvinli** [comment]
@KevinHock 

> I realize you'll have to run this by Yelp folks internally, and that will take time.

Thanks, I'm working on this (it'll take a few days)

**Comment by gpflaum** [comment]
Thank you Yelp and @jpdakran for resuming maintenance of this valuable project. I'll close this issue.

**Comment by lorenzodb1** [comment]
Hello @gpflaum and everyone who took part in this discussion. We're happy that our efforts towards `detect-secrets` has been noticed and that there's no more doubt around our commitment to this project valued by so many.

I wanted to take the opportunity to to reply to @domanchi's question, i.e.

> What are your thoughts of establishing a company-agnostic channel of communication, where the community is able to discuss thoughts in a more real-time capacity? Maybe something like discord?

We currently don't see the need to establish a more real-time communication channel to discuss about `detect-secrets`. While this may surely change in the future as the project evolves, we would like to keep all conversations related to the project on Github for the time being. One thing I'd like to highlight is that we encourage anyone to open an issue if they have any suggestion and/or discussion related to `detect-secrets`. @jpdakran and I routinely check and discuss all issues and PRs opened, so I can promise you they won't go unnoticed.

That being said, we thank you all for your continued interest in `detect-secrets` and for bringing up your concerns around it. This issue/discussion has been formally closed, but feel free to reply to it if you have any further question/comment (or to open a new issue, if you prefer). 

We're looking forward to see your future contributions!
