### ISSUE TITLE
How to filter many filter methods from  a file?

### ISSUE THREAD

**Issue by crazywifi** [Yelp/detect-secrets#481]
Hi, Your tool is great,

Just curious to know how it is possible to filter many methods from a custom_filter.py file?

I have created a custom_filter.py file in which I have given 10 methods for the filter but as per the command we have to mention the method name so what we can do so that the complete custom_filter file will work?

detect-secrets scan --filter custom_filter.py::**is_invalid_secret**

**Comment by BhaskiBuzz** [comment]
Hi @crazywifi ,

I am also trying to write custom filters. could you please share the filter.py you have written so that I can take it as reference. 

Thanks in advance.

**Comment by crazywifi** [comment]
Hello @BhaskiBuzz 

I have created a tutorial on what I did to use the custom filter in the newer version of detect-secret.

https://lazyhacker.medium.com/how-to-add-a-custom-filter-in-the-detect-secrets-yelp-code-for-build-85f1df6d65f5

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
