### ISSUE TITLE
is_likely_id_string filter creates false negatives

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [Yelp/detect-secrets#489]
This filter will eliminate true positives by mistake
https://github.com/Yelp/detect-secrets/blob/b206dc29f274839ebd3c522fed19448c9b8f3f70/detect_secrets/filters/heuristic.py#L71

The following line in a scanned file:
```
DATABASE_URL = "postgres://david:ThisIsNotdavid8789albino@126.234.54.3/somedatabase";
```

Some snippet to test:
```
import re
secret = 'ThisIsNotdavid8789albino'
line = f"DATABASE_URL = 'postgres://david:{secret}@126.234.54.3/somedatabase';"
bool(re.compile(r'id[^a-z0-9]', re.IGNORECASE).search(line, pos=0, endpos=line.index(secret)))
>> True
```

**Comment by domanchi** [comment]
@fproulx-boostsecurity : great find! Thanks for reporting this. When we resolve our current issue with the lack of authorized contributors, hopefully we can resolve this issue.

**Comment by jpdakran** [comment]
Closing as fixed in [526](https://github.com/Yelp/detect-secrets/pull/526)
