### ISSUE TITLE
How  exclude some keyword for KeywordDetector plugin

### ISSUE THREAD

**Issue by vrokida** [Yelp/detect-secrets#494]
Hello !

Please your help. I am using detect-secrets version "1.1.0" and I would like to know how I can exclude some Keyword. I see in the output of the command this: 
```
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    }
```
 So,  I imagine there is a way to add values. 
 
 Here the examples of false positives that I got
` db-password: anything`
 `service_account_secret_name: anything`
 
 
 Thanks in advance

**Comment by lorenzodb1** [comment]
Hello @vrokida, thank you for raising the question.

I believe you can add a regex in your baseline file to exclude those two keywords. Refer to the following snippet if you'd like to see how it would work 
https://github.com/Yelp/detect-secrets/blob/70e6cf69f2d544a49729039a374d86d7b3e472d9/tests/plugins/keyword_test.py#L181-L194

**Comment by jpdakran** [comment]
That is correct. For example to filter keyword db_password which is being flagged. You can update your `.secrets.baseline` to:
```
    {
      "name": "KeywordDetector",
      "keyword_exclude": "db_password"
    },
```
and that secret will be excluded. This `keyword_exclude` property can hold a regex to exclude any keywords that match that specific regex.

**Comment by jpdakran** [comment]
Thanks for your question. I will consider this resolved. If you have any other questions or you do not consider this resolved - please re-open an issue and the team will be happy to assist. Thanks!
