### ISSUE TITLE
Does not work, I'm getting EOF error.

### ISSUE THREAD

**Issue by chkumar77** [Yelp/detect-secrets#525]
Hi All,
I am getting below error, Can anyone help me out.

![image](https://user-images.githubusercontent.com/98515795/160356313-14ef2990-5e52-444c-a43c-da0db7cd5a4b.png)

**Comment by jpdakran** [comment]
@chkumar77 Hello. Can you please post more information regarding the action you are performing. The file you suspect is failing. Any reproducible steps will help us identify the issue and assist in fixing the bug.

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
