### ISSUE TITLE
Test Pypi instance control

### ISSUE THREAD

**Issue by OiCMudkips** [Yelp/detect-secrets#557]
Hi, I notice I was removed from Pypi maintainer list for this package which is probably correct. If anyone from Yelp feels like recovering the package on the [test Pypi instance](https://test.pypi.org/) please feel free to let me know.

https://test.pypi.org/project/detect-secrets/

**Comment by jpdakran** [comment]
Hi @OiCMudkips. Thank you for reaching out. Can you add https://test.pypi.org/user/yelplabs/ as maintainer?

**Comment by jpdakran** [comment]
Got it. Currently we are not using test pypi. We can leave this as is for now. Thanks for reaching out.
