### ISSUE TITLE
False Positive: AWS Access Key for aws:cdk:path

### ISSUE THREAD

**Issue by AjkayAlan** [Yelp/detect-secrets#559]
## Background

I have been using detect-secrets and absolutely love it! Particularly, I use it via [checkov](https://github.com/bridgecrewio/checkov), which scans [AWS CloudFormation](https://aws.amazon.com/cloudformation/) templates (among other things). I am using the [AWS CDK](https://aws.amazon.com/cdk/) to generate my CloudFormation, which adds some metadata

## The Problem

Some CDK metadata in CloudFormation can trigger a false positive on `AWSKeyDetector`. The offending regex is at https://github.com/Yelp/detect-secrets/blob/3c8ee740b1e24f679bc7c7539bfa2aa17f3451d7/detect_secrets/plugins/aws.py#L31

Two examples I have that were from valid generated CloudFormation (from cdk) are:

- `"aws:cdk:path": "VaDataVaultCdkPoc/rBucketKeyCdk/Resource"`
- `"aws:cdk:path": "AuroraRdsStack/DbCluster/Subnets/Default"`

## The Solution

I am not quite sure - in part that I don't have all the context behind the validity of this regex when it was originally introduced/sourced from a third party.

## Final Thoughts

I am willing to make a contribution if someone has a good idea on how to change this to be effective, but still not alert on the scenarios I have put above. Otherwise if someone has a good idea, go for it!

**Comment by lorenzodb1** [comment]
Hi @AjkayAlan! Thank you for your kind words and for reporting this issue. I believe one solution could be to change the regex to look for specific keywords on the left-hand side of the value-assignment statement (such as _key_, I think we already do this in other plugins). This should avoid that metadata to be flagged as sensitive.

@jpdakran do you have any thoughts about this?
