### ISSUE TITLE
Json output format returns an array

### ISSUE THREAD

**Issue by ArisBee** [Yelp/detect-secrets#588]
That's minor, but when I execute something like:

```
detect-secrets audit .secrets.baseline --json --report
```

It will typically returns json objects within an array, for instance if there is no finding it will simply output `[]`. Couldn't it instead return a json object in between curly brackets `{}`?

**Comment by jpdakran** [comment]
Hello @ArisBee. Is there a reason you want this enhancement? The functionality of the audit report is to display a list of secret values which is why it returns an empty list.

**Comment by ArisBee** [comment]
That makes it easier for automated parsing. Now I have to define an exception when nothing is found.

**Comment by lorenzodb1** [comment]
As I mentioned internally, I fully support this enhancement 😄

**Comment by jpdakran** [comment]
@ArisBee Do you want it only in the nothing found case Ex. `{}`. Or just in general?

**Comment by lorenzodb1** [comment]
I would add it in general for consistency. Something like
```
{
    results: [ ... ]
}
```
