### ISSUE TITLE
--exclude-lines option regex bug

### ISSUE THREAD

**Issue by JafarAkhondali** [Yelp/detect-secrets#590]
create `main.yml` with following content:
`checksum: 4b8154b4b1b9ab9de64187d8c4fb4a41`

running: `detect-secrets -C . scan --all-files  --exclude-lines "checksum"` ignores the report, which is right.  
But running a more detailed regex fails to ignore the report:  
`detect-secrets -C . scan --all-files  --exclude-lines "checksum: [a-f0-9]{32}"`

Is this a bug or am I missing something?

version: 1.3.0

**Comment by jpdakran** [comment]
@JafarAkhondali Hello. Excellent question. Are you familiar with the detect-secrets concept of [transformers](https://github.com/Yelp/detect-secrets/blob/master/docs/design.md#transformers)? We use a yaml file transform for enhanced parsing. So what you have above is actually transformed into:

`checksum: "4b8154b4b1b9ab9de64187d8c4fb4a41"`

Therefore your regex does not match. If you update your regex to the following - it would be successfully excluded. 

`checksum: "[a-f0-9]{32}"`

**Comment by jpdakran** [comment]
Thanks for your question. I will consider this resolved. If you have any other questions or you do not consider this resolved - please re-open an issue. Thanks!
