### ISSUE TITLE
Verify function is not getting called, i.e. the the interpreter never goes to verify function.

### ISSUE THREAD

**Issue by KBiru** [Yelp/detect-secrets#603]
Hi,

I have made a custom plugin (a simple regex based just to understand about a custom plugin) and added the verify function for verifying. But for some reason the verify function is never getting invoked. As far as I know the util functions like verify gets invoked automatically if present, don't know if I am missing something here. I am not even getting the print output, see the code snippet below for more info -

```
import re

from detect_secrets.constants import VerifiedResult
from detect_secrets.plugins.base import RegexBasedDetector


class BearerTokenDetector(RegexBasedDetector):
    """Scans for Bearer Tokens."""
    secret_type = 'Bearer Token'

    denylist = [
        # Bearer (Bearer xxxxxxxxx)
        re.compile(r'Bearer\s[\d|a-f]{8}-[\d|a-f]{4}-[\d|a-f]{4}-[\d|a-f]{4}-[\d|a-f]{12}'),
    ]

    def verify(self, secret: str) -> VerifiedResult:
        print(self.denylist)
        if re.fullmatch(self.denylist[0], secret) == None:
            return VerifiedResult.UNVERIFIED
```

Thanks

**Comment by lorenzodb1** [comment]
Hi @KBiru, thank you for bringing up this issue. When working on the 1.3.0 release, we fixed a bug related to the verify function, so I will ask you if you could kindly retest this issue on the latest detect-secrets version and let us know if this is still applicable.

**Comment by KBiru** [comment]
Hi @lorenzodb1 thank you for your response, I have checked it out but still the verify function does not get invoked. The example plugin code I have mentioned earlier is the same. Please let me know if I ma missing something. Also before testing out I have checked the tool version and it is 1.3.0.

**Comment by jpdakran** [comment]
@KBiru Hello. I just tested your code and I do see the verify function getting called. Please find the steps I took to triage your ticket: 

A) Do you have a bearer token in your repo that should be detected?
I updated your plugin with a bearer token: 
`token = "Bearer 11111111-1111-1111-1111-111111111111"`

B) I proceeded to run detect-secrets on the file that I knew the bearer token existed:
`detect-secrets -v scan detect_secrets/plugins/minimal.py > .baseline`

C) I noticed that the secret was being filtered because of 2 filters so I disabled them via: 
`detect-secrets -v scan detect_secrets/plugins/minimal.py --disable-filter detect_secrets.filters.gibberish.should_exclude_secret --disable-filter detect_secrets.filters.heuristic.is_potential_uuid > .baseline`

D) Check the .baseline file - you will see the detected bearer token and you will also see the print statement.

**Comment by KBiru** [comment]
Yes you are right @jpdakran, but I am facing the issue while using it in python script <transient_settings> part to add it as custom plugin, the secrets get detected but the verify() function never gets invoked. Please let me know if any more details are required.

**Comment by jpdakran** [comment]
Can you please post the python script you are using so I can attempt to reproduce the issue you are seeing?

**Comment by jpdakran** [comment]
@KBiru I see the problem. To invoke the verify functionality - the `detect_secrets.filters.common.is_ignored_due_to_verification_policies` must be enabled. Please find sample python script below.
```

from detect_secrets import SecretsCollection
from detect_secrets.settings import transient_settings

secrets = SecretsCollection()
with transient_settings({
    # Only run scans with only these plugins.
    # This format is the same as the one that is saved in the generated baseline.
    'plugins_used': [
        # Example of configuring a built-in plugin
        {
            "name": "BearerTokenDetector",
            "path": "file:///bearer.py"
        },
    ],
    'filters_used': [
        {
        "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
        "min_level": 2
        },
    ]
}) as settings:
    # If we want to make any further adjustments to the created settings object (e.g.
    # disabling default filters), we can do so as such.
    settings.disable_filters(
        'detect_secrets.filters.gibberish.should_exclude_secret',
        'detect_secrets.filters.heuristic.is_potential_uuid',
    )

    secrets.scan_file('./bearer.py')
    
    import json
    print(json.dumps(secrets.json(), indent=2))
```

**Comment by jpdakran** [comment]
Hi @KBiru - Can you please confirm this solves your issue?

**Comment by KBiru** [comment]
Hi @jpdakran yes it did work. I think the documentation needs to be updated a little bit. It was very confusing, thanks a lot for helping out.

**Comment by jpdakran** [comment]
I'm glad it worked. I actually just found this specific solution in the documentation - https://github.com/Yelp/detect-secrets/blob/master/docs/plugins.md#verified-secrets. I will take this feedback and try to make the docs more visible to the community.
