### ISSUE TITLE
Add Discord Bot Token plugin

### ISSUE THREAD

**Issue by syn-4ck** [Yelp/detect-secrets#613]
## Motivation

Discord is a free voice, video, and text chat app that's used by tens of millions of people around the world. One of the pros of this platform is the use of bots to automate a lot of tasks in the `Text chat`. 

I suggest to add a Discord Bot token plugin detector to find this tokens in repositories. GitGuardian metrics reports 2.74 `Discord Bot tokens` per million commits.

## Example (from Discord documentation)

```
Authorization: Bot MTk4NjIyNDgzNDcxOTI1MjQ4.Cl2FMQ.ZnCjm1XVW7vRze4b7Cq4se7kKWs
```

### Discord documentation

https://discord.com/developers/docs/reference#authentication

### Regex to detect

https://gist.github.com/y21/2209ac23ee112b20c9a90ab4ca60ff74#file-scrape-js-L2
https://docs.gitguardian.com/secrets-detection/detectors/specifics/discord_bot_token#details-for-discord-bot-token

## Contribution

- [x] Add a new Discord Bot token plugin
- [x] Add tests
- [x] Pass CI checks

> NOTE: I will create a Pull Request with this changes soon 😄

**Comment by lorenzodb1** [comment]
Hi @syn-4ck, thank you for bringing this idea forward. We're looking forward to seeing your PR 😄
