### ISSUE TITLE
Unrecognized arguments: --gibberish-model

### ISSUE THREAD

**Issue by timurbabs** [Yelp/detect-secrets#650]
I have downloaded gibberish-detector by using:
`pip install detect-secrets[gibberish]`

But it throws me an error when I try to use it:
```
detect-secrets scan --gibberish-model big.model
usage: detect-secrets [-h] [-v] [--version] [-C <path>] [-c NUM_CORES] {scan,audit} ...
detect-secrets: error: unrecognized arguments: --gibberish-model
```

You have an example with this line of code in your README.md

**Comment by jpdakran** [comment]
@timurbabs Hi. Thank you for reporting this. Can you please perform a `detect-secrets scan -h` and verify that the `-- gibberish-model` is a valid arguement? What detect-secrets version are you using?
