### ISSUE TITLE
Custom inline allowlisting comment

### ISSUE THREAD

**Issue by TommasoLencioni** [Yelp/detect-secrets#677]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
Only the lines commented with `# pragma: allowlist secret` and the lines containing one of the [DENYLIST](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/keyword.py#LL43-L43C9) stings are ignored.
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
I would like to specify the inline allowlisting comment format (e.g. `# detect-secrets: ignore` instead of `# pragma: allowlist secret`).

* **What is the motivation / use case for changing the behavior?**
The custom allowlist comment is more clear for future code maintenance.
* **Please tell us about your environment:**
  - detect-secrets Version: 1.4.0
  - Python Version: 3.10
  - OS Version:
  - File type (if applicable):

* **Other information**

**Comment by lorenzodb1** [comment]
Ciao @TommasoLencioni e grazie per l'issue aperta!

>and the lines containing one of the [DENYLIST](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/keyword.py#LL43-L43C9) stings are ignored

Fyi le righe di codice che contengono le strings in `DENYLIST` non vengono ignorate ma vengono segnalate (probabilmente era solo un lapsus, ma vale la pena chiarire).

Detto questo, l'utilizzo di commenti stile `# pragma` per definire un command da eseguire è una cosa abbastanza standard. Per capire l'use-case, il tuo è un problema del tipo che hai diverse librerie che usano commenti simili per cui si possono confondere o possono overlap oppure è più un discorso di rendere immediatamente chiaro che quel commento è legato a `detect-secrets`?

P.S. mi scuso se ho risposto in italiano ma mi capita raramente di parlarlo in questi contesti per cui se posso ne approfitto 😅 

P.S. x2 curiosità personale: a PagoPA usano `detect-secrets`? Chiedo perché ho notato che lavori là.

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
