### ISSUE TITLE
base64 high entropy string false positives

### ISSUE THREAD

**Issue by reddybhaskarvengala** [Yelp/detect-secrets#693]
Detect secret scan identified the below strings as base 64 high entropy strings. These are false positives and the plugin needs improvement. 
callFunctionCheckIfDataAlreadyExistsPerpetualSubinventory
recallNoticesRecallBusinessUnits-validation-group-1297083594-1
assignVariablesOjTabBar1482653721SelectedItem

How to take care of these issues?

**Comment by azizzoaib786** [comment]
Facing the same issue. Any recommendations on the issue?
`"type": "Base64 High Entropy String"`

**Comment by lorenzodb1** [comment]
You can add a comment to ignore these strings. Would that work?

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
