### ISSUE TITLE
Consider using truffleHogRegexes 

### ISSUE THREAD

**Issue by dxa4481** [Yelp/detect-secrets#75]
Hi,

I run truffleHog. I recognize other projects have spun out doing similar things, so a little while ago I broke the regexes into their own package:

https://github.com/dxa4481/truffleHogRegexes

The thinking is I'd ideally like to get the whole community contributing regexes to one place, even if the underlying engine and technology is different.

It's on pypi, feel free to include the regex library.

**Comment by KevinHock** [comment]
I definitely like the idea @dxa4481 😁 (nice to meet you)

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
