### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by kytwb** [Yelp/detect-secrets#77]
I've been trying to run this tool against the [discourse](https://github.com/discourse/discourse) repository. 
It seems to get stuck when encountering [this file](https://github.com/discourse/discourse/blob/master//plugins/discourse-narrative-bot/lib/discourse_narrative_bot/certificate_generator.rb):

```
[secrets_collection]    INFO    Checking file: ./plugins/discourse-narrative-bot/lib/discourse_narrative_bot/certificate_generator.rb
```

Any workaround/suggestion?

**Comment by KevinHock** [comment]
Hi @kytwb, sorry for the late reply, I strongly suspect that it is due to https://github.com/Yelp/detect-secrets/issues/79, we'll be working on fixing that soon.

**Comment by domanchi** [comment]
Hi @kytwb,

We've merged an update to the BasicAuth plugin, which significantly improves the performance of it. That will go out in the next release, and will work with the file you specified.

If you want, you can pull master and run it against repo, or you can try running the scan with `--no-basic-auth-plugin`.

**Comment by KevinHock** [comment]
(Bumped to version `0.10.3`)

**Comment by kytwb** [comment]
Thanks for the reactivity guys 🎉

**Comment by streichsbaer** [comment]
> Hi @kytwb,
> 
> We've merged an update to the BasicAuth plugin, which significantly improves the performance of it. That will go out in the next release, and will work with the file you specified.
> 
> If you want, you can pull master and run it against repo, or you can try running the scan with `--no-basic-auth-plugin`.

Just tried the cmd line switch and it didn't work. To disable plugins use `--no-{plugin-name}` e.g `--no-basic-auth`, or `--no-keyword.

**Comment by domanchi** [comment]
@streichsbaer : ah, whoops! Thanks for the correction. If interested, the disable command line flags are found here: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/usage.py#L225
