### ISSUE TITLE
Fix README so copy/paste works

### ISSUE THREAD

**Issue by matt-horwood-mayden** [Yelp/detect-secrets#771]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
* When copying commands form the README
* it has the `$` at the start
* that fails when paste into a termain

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
* following the docs

* **Please tell us about your environment:**
  - detect-secrets Version: 1.4.0
  - Python Version: 3.10.13
  - OS Version: MacOS 14.2
  - File type (if applicable): NA

* **Other information**

![image](https://github.com/Yelp/detect-secrets/assets/17851531/fce8c681-a3ef-4d58-9b03-deb76aa45326)
![image](https://github.com/Yelp/detect-secrets/assets/17851531/3b682502-4183-4a9c-a567-9793fda9bfa7)

**Comment by lorenzodb1** [comment]
Hi @matt-horwood-mayden, it's actually a pretty standard practice to add `$` before commands. If you need to copy/paste, you can select the command with your mouse without the symbol.
