### ISSUE TITLE
Supported languages?

### ISSUE THREAD

**Issue by deeplook** [Yelp/detect-secrets#772]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behavior?**

* It is not stated if this tool only supports Python as the only programming language. 

* **What is the expected behavior?**

* It would be nice to make an explicit statement in the README. Then it would be immediately clear without any need to inspect the source code.

**Comment by lorenzodb1** [comment]
Hi @deeplook, thank you for opening this issue. I'm not sure where you got that, but `detect-secrets` supports multiple languages, as (maybe not truly explicitly) mentioned in the docs as well.

**Comment by CyanFi** [comment]
I have the same question too. Does the tool support java?

**Comment by lorenzodb1** [comment]
@CyanFi yes, you can use `detect-secrets` on Java files too.
