### ISSUE TITLE
Getting detect-secrets: command not found error

### ISSUE THREAD

**Issue by aakanshaverma1310** [Yelp/detect-secrets#792]
From past 15 days, we are getting below error while using detect secret scan tool. Earlier it was working fine for me. 

command - 
`detect-secrets scan --force-use-all-plugins --all-files  $(System.DefaultWorkingDirectory)/repo-name  > $(Pipeline.Workspace)/detect-secrets.json`

Any leads who can help me here to fix the issue? Thanks in advance. 

![image](https://github.com/Yelp/detect-secrets/assets/45385925/bb07fbbe-2e20-428f-b772-afb919d9d32f)

**Comment by aakanshaverma1310** [comment]
@gpflaum @lorenzodb1  - Any suggestion on above?

**Comment by gpflaum** [comment]
It looks like detect-secrets is simply not on the path in your build environment. I don't know what build pipeline tools you are using. Did your build move from a machine that had detect-secrets installed to one that doesn't? I don't see any indication that detect-secrets is doing anything wrong, just that your build is failing to find it to run it.

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
