### ISSUE TITLE
Request: Push a new tag

### ISSUE THREAD

**Issue by jmctune** [Yelp/detect-secrets#807]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
This repository hasn't had a new tag pushed since October 2022, but there have been several PRs and dependency updates merged since then. I was going through my pre-commit hooks and noticed this one hasn't had an update in quite a while.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

* **What is the expected behavior?**
N/A

* **What is the motivation / use case for changing the behavior?**
Stay up to date on new changes.

* **Please tell us about your environment:**
  - detect-secrets Version: N/A
  - Python Version: N/A
  - OS Version: N/A
  - File type (if applicable): N/A

* **Other information**

Thank you for maintaining this pre-commit hook.

**Comment by lorenzodb1** [comment]
@jmctune you're most definitely right. We're aware of this and I can promise you that we'll make a release by the end of this month. Apologies again, but we've been quite busy in the past months.

**Comment by lorenzodb1** [comment]
@jmctune detect-secrets v1.5 is out! I'll close this issue, but thank you again for your patience!
