### ISSUE TITLE
Keyword Detector is not used in 0.10.5

### ISSUE THREAD

**Issue by Tioborto** [Yelp/detect-secrets#97]
Hello, 

When i run a scan on a repo, KeywordDetector is not used. 
If it's normal, why it's disable ? 

> {
  "exclude_regex": null,
  "generated_at": "2018-11-26T09:42:29Z",
  "plugins_used": [
    {
      "base64_limit": 4.5,
      "name": "Base64HighEntropyString"
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "hex_limit": 3,
      "name": "HexHighEntropyString"
    },
    {
      "name": "PrivateKeyDetector"
    }
  ],
  "results": {},
  "version": "0.10.5"
}

Thank you

**Comment by Tioborto** [comment]
Hello @KevinHock , 
For when do you think it will be over ? We are very eager to test this new version

**Comment by KevinHock** [comment]
Sorry for the late reply @Tioborto, we're hoping by the end of December, after doing more internal testing.

**Comment by rhinoceros** [comment]
I found the same problem.
# pre-commit 1.13.0
# .pre-commit-config.yaml
```
-   repo: git@github.com:Yelp/detect-secrets
    rev: v0.11.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*
```

# a.conf
``` 
user: wangxn
xx=dXNlcjogd2FuZ3huCnh4OiAKcGFzc3dvcmQ6IHdhbmd4bjEyMwo=
password: wangxn123
username: abc
password: aaaa
password: 123456
API_KEY = "blah-blah-but-actually-not-secret"
```


```
bogon:my-git-repo User1$ git add a.conf 
bogon:my-git-repo User1$ git commit -m"test"
Detect secrets...........................................................Passed
[xx 589b342] test
 1 file changed, 1 insertion(+), 2 deletions(-)
```

**Comment by KevinHock** [comment]
Finally released the new version of Keyword detector in `0.11.2`, let me know what you think @rhinoceros @Tioborto @andrewscott-vibrato :) 👍  🥂 🎉 🎈 🎂

**Comment by rhinoceros** [comment]
> Finally released the new version of Keyword detector in `0.11.2`, let me know what you think @rhinoceros @Tioborto @andrewscott-vibrato :) 👍 🥂 🎉 🎈 🎂

It's works now. Thanks.
